if (GetLocale()=="zhTW") then

CCWATCH_VERSION = "11000.2"
CCWATCH_FULLVERSION = "CCWatch v"..CCWATCH_VERSION

-- CN

CCWATCH_DESCRIPTION = "顯示一個支持全職業的控制技能，Buff，Debuff監視條."

CCWATCH_PROFILE_TEXT = "配置文件: "

CCWATCH_EFFECT = "效果"
CCWATCH_NAME = "名稱"
CCWATCH_DURATION = "持續時間"
CCWATCH_RESET = "重置"
CCWATCH_ADD = "增加"
CCWATCH_MODIFY = "修改"
CCWATCH_EDIT = "編輯"
CCWATCH_DELETE = "刪除"
CCWATCH_LEARN_DELETE_PROMPT = "你確實想要刪除該效果嗎？ "
CCWATCH_REMOVED_NOTICE = "已刪除技能效果 : "
CCWATCH_TYPE = "類型"
CCWATCH_GROUP = "組"
CCWATCH_DR = "技能效果遞減"
CCWATCH_MONITOR = "顯示監視條"
CCWATCH_WARN = "顯示提醒信息"
CCWATCH_ADDEDMODIFIED = "已增加/修改."

CCWATCH_OPTIONS_BARS_TAB = "監視條"
CCWATCH_OPTIONS_EFFECTS_TAB = "監控選項"
CCWATCH_OPTIONS_LEARN_TAB = "自學習"

CCWATCH_OPTIONS_TITLE = "CCWatch 選項";
CCWATCH_OPTIONS_TRANS = "透明度";
CCWATCH_OPTIONS_SCALE = "縮放";
CCWATCH_OPTIONS_DONE = "完成";
CCWATCH_OPTIONS_UNLOCK = "解鎖";
CCWATCH_OPTIONS_WIDTH = "寬度";
CCWATCH_OPTIONS_INVERT = "反向";
CCWATCH_OPTIONS_LEADINGTIMER = "計時器靠左顯示"
CCWATCH_OPTIONS_ARCANIST = "祕法師套裝效果";

CCWATCH_OPTIONS_WARN_APPLIED = "技能觸發時顯示提醒信息"
CCWATCH_OPTIONS_WARN_FADED = "技能消失時顯示提醒信息"
CCWATCH_OPTIONS_WARN_BROKEN = "技能被打斷時顯示提醒信息"
CCWATCH_OPTIONS_WARN_LOWTIME = "技能將消失時顯示提醒信息"

CCWATCH_OPTIONS_MAGE = "法師監控"
CCWATCH_OPTIONS_PRIEST = "牧師監控"
CCWATCH_OPTIONS_DRUID = "德魯伊監控"
CCWATCH_OPTIONS_HUNTER = "獵人監控"
CCWATCH_OPTIONS_PALADIN = "聖騎士監控"
CCWATCH_OPTIONS_WARLOCK = "術士監控"
CCWATCH_OPTIONS_WARRIOR = "戰士監控"
CCWATCH_OPTIONS_ROGUE = "盜賊監控"
CCWATCH_OPTIONS_SHAMAN = "薩滿監控"
CCWATCH_OPTIONS_MISC = "其他的監控"

CCWATCH_OPTION_STYLE_CURRENT = "當前目標"
CCWATCH_OPTION_STYLE_RECENT = "近期目標"
CCWATCH_OPTION_STYLE_ALL = "任何生物/敵人"

CCWATCH_OPTION_GROWTH_OFF = "監視條不增加"
CCWATCH_OPTION_GROWTH_UP = "監視條自下而上增加"
CCWATCH_OPTION_GROWTH_DOWN = "監視條自上而下增加"

CCWATCH_OPTION_TIMERS_OFF = "計時器關閉"
CCWATCH_OPTION_TIMERS_ON = "計時器開啟"
CCWATCH_OPTION_TIMERS_REVERSE = "計時器倒計時"

CCWATCH_OPTION_DR_NEVER = "從不"
CCWATCH_OPTION_DR_MOBPLAYERS = "怪物＋玩家"
CCWATCH_OPTION_DR_PLAYERS = "玩家"

CCWATCH_OPTIONS_MONITOR_CC = "監視控制技能"
CCWATCH_OPTIONS_MONITOR_DEBUFF = "監視減益魔法"
CCWATCH_OPTIONS_MONITOR_BUFF = "監視增益魔法"

CCWATCH_OPTIONS_COLOROVERTIME = "監視條顏色隨時間漸變"
CCWATCH_OPTIONS_USECOLOR = "自定義監視條顏色"

CCWATCH_OPTIONS_EMOTE = "表情"
CCWATCH_OPTIONS_SAY = "說"
CCWATCH_OPTIONS_PARTY = "隊伍"
CCWATCH_OPTIONS_RAID = "團隊"
CCWATCH_OPTIONS_YELL = "喊"
CCWATCH_OPTIONS_CHANNEL = "頻道"
CCWATCH_OPTIONS_CC = "控制技能"
CCWATCH_OPTIONS_DEBUFF = "減益魔法"
CCWATCH_OPTIONS_BUFF = "增益魔法"

CCWATCH_WARN_EMOTE = "注意 ";
CCWATCH_WARN_LOWTIME = "[%s] 即將不再被 [%s] 影響，還剩 %d 秒。"
CCWATCH_WARN_APPLIED = "[%s] 被 [%s] 擊中."
CCWATCH_WARN_FADED = "[%s] 不再被 [%s]影響 (技能消失)."
CCWATCH_WARN_BROKEN = "[%s] 不再被 [%s]影響(技能被打斷)."

-- Priest
CCWATCH_SHACKLE = "束縛不死生物"
CCWATCH_PSYCHICSCREAM = "心靈尖嘯"
CCWATCH_BLACKOUT = "昏闕"
CCWATCH_SHADOWWORDPAIN = "暗言術：痛"
CCWATCH_POWERWORDSHIELD = "真言術：盾"
CCWATCH_DEVOURINGPLAGUE = "吞噬瘟疫"
CCWATCH_WEAKENEDSOUL = "虛弱靈魂"
CCWATCH_RENEW ="恢復"
CCWATCH_HOLYFIRE = "聖火"
CCWATCH_POWERINFUSION = "能量灌注"

-- Mage
CCWATCH_POLYMORPH = "變形術"
CCWATCH_FROSTNOVA = "冰霜新星"
CCWATCH_FROSTBITE = "霜寒刺骨"
CCWATCH_ICEBLOCK = "寒冰屏障"
CCWATCH_FROSTBOLT = "寒冰箭"
CCWATCH_CONEOFCOLD = "冰錐術"
CCWATCH_COUNTERSPELL = "法術反制 - 沉默"
CCWATCH_FIREBALL = "火球術"
CCWATCH_PYROBLAST = "炎爆術"
CCWATCH_IGNITE = "引燃"
CCWATCH_FLAMESTRIKE = "烈焰風暴"
CCWATCH_BLASTWAVE = "沖擊波"
CCWATCH_FROSTARMOR = "冰凍"
CCWATCH_DETECTMAGIC = "偵測魔法"
CCWATCH_EVOCATION = "喚醒"
CCWATCH_ARCANEPOWER = "祕法能量"

-- Paladin
CCWATCH_HOJ = "制裁之錘"
CCWATCH_TURNUNDEAD = "超度不死族"
CCWATCH_REPENTANCE = "懺悔"
CCWATCH_DIVINESHIELD = "神聖之盾"
CCWATCH_BOPROTECTION = "保護祝福"
CCWATCH_BOFREEDOM = "自由祝福"

-- Warlock
CCWATCH_FEAR = "恐懼術"
CCWATCH_BANISH = "放逐術"
CCWATCH_SEDUCE = "誘惑"
CCWATCH_HOWLOFTERROR = "恐懼嚎叫"
CCWATCH_DEATHCOIL = "死亡纏繞"
CCWATCH_IMMOLATE = "獻祭"
CCWATCH_CORRUPTION = "腐蝕術"
CCWATCH_CURSEOFRECKLESSNESS = "魯莽詛咒"
CCWATCH_CURSEOFAGONY = "痛苦詛咒"
CCWATCH_CURSEOFWEAKNESS = "虛弱詛咒"
CCWATCH_CURSEOFTONGUES = "語言詛咒"
CCWATCH_CURSEOFSHADOW = "暗影詛咒"
CCWATCH_CURSEOFELEMENTS = "元素詛咒"
CCWATCH_CURSEOFEXHAUSTION = "疲勞詛咒"
CCWATCH_CURSEOFDOOM = "厄運詛咒"
CCWATCH_SIPHONLIFE = "生命虹吸"
CCWATCH_IMPROVEDSHADOWBOLT = "強化暗影箭"
CCWATCH_SACRIFICE = "犧牲"
CCWATCH_SPELLSTONE = "法術石"
CCWATCH_SPELLLOCK = "法術封鎖"


-- Druid
CCWATCH_HIBERNATE = "休眠"
CCWATCH_ROOTS = "糾纏根鬚"
CCWATCH_POUNCE = "突襲"
CCWATCH_BASH = "重擊"
CCWATCH_FERALCHARGE = "野性沖鋒"
CCWATCH_IMPSTARFIRE = "星火昏迷"
CCWATCH_MOONFIRE = "月火術"
CCWATCH_INSECTSWARM = "蟲群"
CCWATCH_NATURESGRASP = "自然之握"
CCWATCH_REJUVENATION = "回春術"
CCWATCH_DASH = "急奔"
CCWATCH_FAERIEFIRE = "精靈之火"
CCWATCH_FAERIEFIREFERAL = "精靈之火（野性）"
CCWATCH_INNERVATE = "啟動"
CCWATCH_BARKSKIN = "樹皮術"
CCWATCH_REGROWTH = "愈合"
CCWATCH_FREGEN = "狂暴回復"


-- Hunter
CCWATCH_FREEZINGTRAP = "冰凍陷阱效果"
CCWATCH_FREEZINGTRAP_SPELL = "冰凍陷阱"
CCWATCH_SCAREBEAST = "恐嚇野獸"
CCWATCH_IMPCS = "強化震蕩射擊"
CCWATCH_SCATTERSHOT = "驅散射擊"
CCWATCH_INTIMIDATION = "脅迫"
CCWATCH_COUNTERATTACK = "反擊"
CCWATCH_WYVERNSTING = "翼龍釘刺"
CCWATCH_IMPROVEDWINGCLIP = "強化摔絆"
CCWATCH_ENTRAPMENT = "誘捕"
CCWATCH_SERPENTSTING = "毒蛇釘刺"
CCWATCH_DETERRENCE = "威懾"
CCWATCH_RAPIDFIRE = "急速射擊"

-- Warrior
CCWATCH_INTERCEPT = "攔截昏迷"
CCWATCH_MACESPE = "錘係專精"
CCWATCH_IMPHAMSTRING = "強化斷筋"
CCWATCH_INTIMIDATINGSHOUT = "破膽怒吼"
CCWATCH_IMPREVENGE = "復仇昏迷"
CCWATCH_CONCUSSIONBLOW = "震蕩猛擊"
CCWATCH_BERSERKERRAGE = "狂暴之怒"
CCWATCH_BLOODRAGE = "血性狂暴"
CCWATCH_REND = "撕裂"
CCWATCH_DISARM = "繳械"
CCWATCH_LASTSTAND = "破釜沉舟"
CCWATCH_RETALIATION = "反擊風暴"
CCWATCH_SHIELDWALL = "盾牆"
CCWATCH_DEATHWISH = "死亡之愿"
CCWATCH_IMPSHIELDBASH = "盾擊 - 沉默"
CCWATCH_MORTALSTRIKE = "致死打擊"
CCWATCH_RECKLESSNESS = "魯莽"
CCWATCH_HAMSTRING = "斷筋"

--Rogue
CCWATCH_GOUGE = "鑿擊"
CCWATCH_BLIND = "致盲"
CCWATCH_KS = "腎擊"
CCWATCH_CS = "偷襲"
CCWATCH_SAP = "悶棍"
CCWATCH_RUPTURE = "割裂"
CCWATCH_GAROTTE = "絞喉"
CCWATCH_RIPOSTE = "破甲"
CCWATCH_IMPROVEDKICK = "腳踢 - 沉默"
CCWATCH_ADRENALINERUSH = "沖動"
CCWATCH_EVASION = "閃避"
CCWATCH_ROGUESPRINT = "疾跑"
CCWATCH_BLADEFLURRY = "劍刃亂舞"
CCWATCH_CRIPPLINGP = "致殘毒藥"
CCWATCH_DEADLYP = "致命毒藥"

-- Shaman
CCWATCH_FROSTSHOCK = "冰霜震擊"
CCWATCH_FLAMESHOCK = "烈焰震擊"
CCWATCH_FROSTBRANDWEAPON = "冰封武器"
CCWATCH_STORMSTRIKE = "風暴打擊"

-- Miscellaneous
CCWATCH_WARSTOMP = "戰爭踐踏"
CCWATCH_SLEEP = "睡眠"
CCWATCH_NETOMATIC = "撒網器"
CCWATCH_ROCKETHELM = "高爆炸彈"

CCWATCH_WOTF = "不死族意志"
CCWATCH_PERCEPTION = "感知"

CCWATCH_RANK = "等級"
CCWATCH_DETECTED = "已檢測到"
CCWATCH_NOTDETECTED = "未檢測到"

CCWATCH_ENABLED = "CCWatch 啟用"
CCWATCH_DISABLED = "CCWatch 禁用"

CCWATCH_LOCKED = "CCWatch 鎖定"
CCWATCH_UNLOCKED = "CCWatch 解鎖"

CCWATCH_INVERSION_ON = "CCWatch 反向開啟"
CCWATCH_INVERSION_OFF = "CCWatch 反向關閉"

CCWATCH_STYLE_CURRENT = "僅監視當前目標"
CCWATCH_STYLE_RECENT = "監視近期目標"
CCWATCH_STYLE_ALL = "監視所有目標"

CCWATCH_GROW_OFF = "CCWatch 監視條不增加"
CCWATCH_GROW_UP = "CCWatch 監視條向上增加"
CCWATCH_GROW_DOWN = "CCWatch 監視條向下增加"

CCWATCH_TIMERS_OFF = "計時器關閉"
CCWATCH_TIMERS_ON = "計時器開啟"
CCWATCH_TIMERS_REVERSE = "計時器倒計時"

CCWATCH_ARCANIST_ON = "祕法師套裝效果可用(+15秒到 "..CCWATCH_POLYMORPH.." 魔法)"
CCWATCH_ARCANIST_OFF = "祕法師套裝效果禁用"

CCWATCH_COLOROVERTIME_ON = "監視條顏色隨時間漸變開啟"
CCWATCH_COLOROVERTIME_OFF = "監視條顏色隨時間漸變關閉"
CCWATCH_LEADINGTIMER_ON = "計時器位置: 靠左"
CCWATCH_LEADINGTIMER_OFF = "計時器位置：靠右"
CCWATCH_WARNCC_SETTO = "提醒信息的輸出設置為："
CCWATCH_WARNCC_CUSTOM = "自定義提醒信息頻道生效：(標準的提醒信息頻道 EMOTE, SAY, PARTY, RAID, YELL): "
CCWATCH_WARN_DISABLED = "提醒信息關閉"
CCWATCH_WARN_ENABLED = "提醒信息開啟"

CCWATCH_SCALE = "CCWatch 比例設置為 "

CCWATCH_WIDTH = "CCWatch 寬度設置為 "

CCWATCH_ALPHA = "CCWatch 透明度設置為 "

CCWATCH_LOADED = " 已載入 - /ccw"

CCWATCH_HELP1  = " : 使用 - /ccw 指令"
CCWATCH_HELP2  = "指令："
CCWATCH_HELP3  = " on     : 啟用 CCWatch"
CCWATCH_HELP4  = " off    : 禁用 CCWatch"
CCWATCH_HELP5  = " lock   : 鎖定 CCWatch 並啟用"
CCWATCH_HELP6  = " unlock : 解鎖 CCWatch 使可移動"
CCWATCH_HELP7  = " u      : 更新升級的技能等級"
CCWATCH_HELP8 = " print  : 列出目前配置"
CCWATCH_HELP9 = " invert : 將監視條反向"
CCWATCH_HELP10 = " scale  : 定義 CCWatch 比例, 從 0.25 到 3.0"
CCWATCH_HELP11 = " width  : 設置監視條寬度, 從 50 到 300"
CCWATCH_HELP12 = " alpha  : 設置監視條透明度, 從 0 到 1"
CCWATCH_HELP13 = " grow   : 設置監視條增加關閉、向上或向下"
CCWATCH_HELP14 = " config : 顯示配置窗口"
CCWATCH_HELP15 = " timers : 設置計時器顯示關閉，開啟或倒計時。有效參數為off, on 和 rev。"
CCWATCH_HELP16 = " warn   : 開始/關閉 提醒信息"
CCWATCH_HELP17 = " warncc : 設置提醒信息使用的頻道(EMOTE, SAY, PARTY, RAID, YELL 或自定義)"

end