CCWATCH_VERSION = "11000.2"
CCWATCH_FULLVERSION = "CCWatch v"..CCWATCH_VERSION

-- CN

CCWATCH_DESCRIPTION = "显示一个支持全职业的控制技能，Buff，Debuff监视条."

CCWATCH_PROFILE_TEXT = "配置文件: "

CCWATCH_EFFECT = "效果"
CCWATCH_NAME = "名称"
CCWATCH_DURATION = "持续时间"
CCWATCH_RESET = "重置"
CCWATCH_ADD = "增加"
CCWATCH_MODIFY = "修改"
CCWATCH_EDIT = "编辑"
CCWATCH_DELETE = "删除"
CCWATCH_LEARN_DELETE_PROMPT = "你确实想要删除该效果吗？ "
CCWATCH_REMOVED_NOTICE = "已删除技能效果 : "
CCWATCH_TYPE = "类型"
CCWATCH_GROUP = "组"
CCWATCH_DR = "技能效果递减"
CCWATCH_MONITOR = "显示监视条"
CCWATCH_WARN = "显示提醒信息"
CCWATCH_ADDEDMODIFIED = "已增加/修改."

CCWATCH_OPTIONS_BARS_TAB = "监视条"
CCWATCH_OPTIONS_EFFECTS_TAB = "监控选项"
CCWATCH_OPTIONS_LEARN_TAB = "自学习"

CCWATCH_OPTIONS_TITLE = "CCWatch 选项";
CCWATCH_OPTIONS_TRANS = "透明度";
CCWATCH_OPTIONS_SCALE = "缩放";
CCWATCH_OPTIONS_DONE = "完成";
CCWATCH_OPTIONS_UNLOCK = "解锁";
CCWATCH_OPTIONS_WIDTH = "宽度";
CCWATCH_OPTIONS_INVERT = "反向";
CCWATCH_OPTIONS_LEADINGTIMER = "计时器靠左显示"
CCWATCH_OPTIONS_ARCANIST = "奥术师套装效果";

CCWATCH_OPTIONS_WARN_APPLIED = "技能触发时显示提醒信息"
CCWATCH_OPTIONS_WARN_FADED = "技能消失时显示提醒信息"
CCWATCH_OPTIONS_WARN_BROKEN = "技能被打断时显示提醒信息"
CCWATCH_OPTIONS_WARN_LOWTIME = "技能将消失时显示提醒信息"

CCWATCH_OPTIONS_MAGE = "法师监控"
CCWATCH_OPTIONS_PRIEST = "牧师监控"
CCWATCH_OPTIONS_DRUID = "德鲁伊监控"
CCWATCH_OPTIONS_HUNTER = "猎人监控"
CCWATCH_OPTIONS_PALADIN = "圣骑士监控"
CCWATCH_OPTIONS_WARLOCK = "术士监控"
CCWATCH_OPTIONS_WARRIOR = "战士监控"
CCWATCH_OPTIONS_ROGUE = "盗贼监控"
CCWATCH_OPTIONS_SHAMAN = "萨满监控"
CCWATCH_OPTIONS_MISC = "其他的监控"

CCWATCH_OPTION_STYLE_CURRENT = "当前目标"
CCWATCH_OPTION_STYLE_RECENT = "近期目标"
CCWATCH_OPTION_STYLE_ALL = "任何生物/敌人"

CCWATCH_OPTION_GROWTH_OFF = "监视条不增加"
CCWATCH_OPTION_GROWTH_UP = "监视条自下而上增加"
CCWATCH_OPTION_GROWTH_DOWN = "监视条自上而下增加"

CCWATCH_OPTION_TIMERS_OFF = "计时器关闭"
CCWATCH_OPTION_TIMERS_ON = "计时器开启"
CCWATCH_OPTION_TIMERS_REVERSE = "计时器倒计时"

CCWATCH_OPTION_DR_NEVER = "从不"
CCWATCH_OPTION_DR_MOBPLAYERS = "怪物＋玩家"
CCWATCH_OPTION_DR_PLAYERS = "玩家"

CCWATCH_OPTIONS_MONITOR_CC = "监视控制技能"
CCWATCH_OPTIONS_MONITOR_DEBUFF = "监视减益魔法"
CCWATCH_OPTIONS_MONITOR_BUFF = "监视增益魔法"

CCWATCH_OPTIONS_COLOROVERTIME = "监视条颜色随时间渐变"
CCWATCH_OPTIONS_USECOLOR = "自定义监视条颜色"

CCWATCH_OPTIONS_EMOTE = "表情"
CCWATCH_OPTIONS_SAY = "说"
CCWATCH_OPTIONS_PARTY = "队伍"
CCWATCH_OPTIONS_RAID = "团队"
CCWATCH_OPTIONS_YELL = "喊"
CCWATCH_OPTIONS_CHANNEL = "频道"
CCWATCH_OPTIONS_CC = "控制技能"
CCWATCH_OPTIONS_DEBUFF = "减益魔法"
CCWATCH_OPTIONS_BUFF = "增益魔法"

CCWATCH_WARN_EMOTE = "注意 ";
CCWATCH_WARN_LOWTIME = "[%s] 即将不再被 [%s] 影响，还剩 %d 秒。"
CCWATCH_WARN_APPLIED = "[%s] 被 [%s] 击中."
CCWATCH_WARN_FADED = "[%s] 不再被 [%s]影响 (技能消失)."
CCWATCH_WARN_BROKEN = "[%s] 不再被 [%s]影响(技能被打断)."

-- Priest
CCWATCH_SHACKLE = "束缚亡灵"
CCWATCH_PSYCHICSCREAM = "心灵尖啸"
CCWATCH_BLACKOUT = "昏阙"
CCWATCH_SHADOWWORDPAIN = "暗言术：痛"
CCWATCH_POWERWORDSHIELD = "真言术：盾"
CCWATCH_DEVOURINGPLAGUE = "吞噬瘟疫"
CCWATCH_WEAKENEDSOUL = "虚弱灵魂"
CCWATCH_RENEW ="恢复"
CCWATCH_HOLYFIRE = "神圣之火"
CCWATCH_POWERINFUSION = "能量灌注"

-- Mage
CCWATCH_POLYMORPH = "变形术"
CCWATCH_FROSTNOVA = "冰霜新星"
CCWATCH_FROSTBITE = "霜寒刺骨"
CCWATCH_ICEBLOCK = "寒冰屏障"
CCWATCH_FROSTBOLT = "寒冰箭"
CCWATCH_CONEOFCOLD = "冰锥术"
CCWATCH_COUNTERSPELL = "法术反制 - 沉默"
CCWATCH_FIREBALL = "火球术"
CCWATCH_PYROBLAST = "炎爆术"
CCWATCH_IGNITE = "引燃"
CCWATCH_FLAMESTRIKE = "烈焰风暴"
CCWATCH_BLASTWAVE = "冲击波"
CCWATCH_FROSTARMOR = "冰冻"
CCWATCH_DETECTMAGIC = "侦测魔法"
CCWATCH_EVOCATION = "唤醒"
CCWATCH_ARCANEPOWER = "奥术能量"

-- Paladin
CCWATCH_HOJ = "制裁之锤"
CCWATCH_TURNUNDEAD = "超度亡灵"
CCWATCH_REPENTANCE = "忏悔"
CCWATCH_DIVINESHIELD = "神圣之盾"
CCWATCH_BOPROTECTION = "保护祝福"
CCWATCH_BOFREEDOM = "自由祝福"

-- Warlock
CCWATCH_FEAR = "恐惧术"
CCWATCH_BANISH = "放逐术"
CCWATCH_SEDUCE = "诱惑"
CCWATCH_HOWLOFTERROR = "恐惧嚎叫"
CCWATCH_DEATHCOIL = "死亡缠绕"
CCWATCH_IMMOLATE = "献祭"
CCWATCH_CORRUPTION = "腐蚀术"
CCWATCH_CURSEOFRECKLESSNESS = "鲁莽诅咒"
CCWATCH_CURSEOFAGONY = "痛苦诅咒"
CCWATCH_CURSEOFWEAKNESS = "虚弱诅咒"
CCWATCH_CURSEOFTONGUES = "语言诅咒"
CCWATCH_CURSEOFSHADOW = "暗影诅咒"
CCWATCH_CURSEOFELEMENTS = "元素诅咒"
CCWATCH_CURSEOFEXHAUSTION = "疲劳诅咒"
CCWATCH_CURSEOFDOOM = "厄运诅咒"
CCWATCH_SIPHONLIFE = "生命虹吸"
CCWATCH_IMPROVEDSHADOWBOLT = "强化暗影箭"
CCWATCH_SACRIFICE = "牺牲"
CCWATCH_SPELLSTONE = "法术石"
CCWATCH_SPELLLOCK = "法术封锁"


-- Druid
CCWATCH_HIBERNATE = "休眠"
CCWATCH_ROOTS = "纠缠根须"
CCWATCH_POUNCE = "突袭"
CCWATCH_BASH = "重击"
CCWATCH_FERALCHARGE = "野性冲锋"
CCWATCH_IMPSTARFIRE = "星火昏迷"
CCWATCH_MOONFIRE = "月火术"
CCWATCH_INSECTSWARM = "虫群"
CCWATCH_NATURESGRASP = "自然之握"
CCWATCH_REJUVENATION = "回春术"
CCWATCH_DASH = "急奔"
CCWATCH_FAERIEFIRE = "精灵之火"
CCWATCH_FAERIEFIREFERAL = "精灵之火（野性）"
CCWATCH_INNERVATE = "激活"
CCWATCH_BARKSKIN = "树皮术"
CCWATCH_REGROWTH = "愈合"
CCWATCH_FREGEN = "狂暴回复"


-- Hunter
CCWATCH_FREEZINGTRAP = "冰冻陷阱效果"
CCWATCH_FREEZINGTRAP_SPELL = "冰冻陷阱"
CCWATCH_SCAREBEAST = "恐吓野兽"
CCWATCH_IMPCS = "强化震荡射击"
CCWATCH_SCATTERSHOT = "驱散射击"
CCWATCH_INTIMIDATION = "胁迫"
CCWATCH_COUNTERATTACK = "反击"
CCWATCH_WYVERNSTING = "翼龙钉刺"
CCWATCH_IMPROVEDWINGCLIP = "强化摔绊"
CCWATCH_ENTRAPMENT = "诱捕"
CCWATCH_SERPENTSTING = "毒蛇钉刺"
CCWATCH_DETERRENCE = "威慑"
CCWATCH_RAPIDFIRE = "急速射击"

-- Warrior
CCWATCH_INTERCEPT = "拦截昏迷"
CCWATCH_MACESPE = "锤系专精"
CCWATCH_IMPHAMSTRING = "强化断筋"
CCWATCH_INTIMIDATINGSHOUT = "破胆怒吼"
CCWATCH_IMPREVENGE = "复仇昏迷"
CCWATCH_CONCUSSIONBLOW = "震荡猛击"
CCWATCH_BERSERKERRAGE = "狂暴之怒"
CCWATCH_BLOODRAGE = "血性狂暴"
CCWATCH_REND = "撕裂"
CCWATCH_DISARM = "缴械"
CCWATCH_LASTSTAND = "破釜沉舟"
CCWATCH_RETALIATION = "反击风暴"
CCWATCH_SHIELDWALL = "盾墙"
CCWATCH_DEATHWISH = "死亡之愿"
CCWATCH_IMPSHIELDBASH = "盾击 - 沉默"
CCWATCH_MORTALSTRIKE = "致死打击"
CCWATCH_RECKLESSNESS = "鲁莽"
CCWATCH_HAMSTRING = "断筋"

--Rogue
CCWATCH_GOUGE = "凿击"
CCWATCH_BLIND = "致盲"
CCWATCH_KS = "肾击"
CCWATCH_CS = "偷袭"
CCWATCH_SAP = "闷棍"
CCWATCH_RUPTURE = "割裂"
CCWATCH_GAROTTE = "绞喉"
CCWATCH_RIPOSTE = "破甲"
CCWATCH_IMPROVEDKICK = "脚踢 - 沉默"
CCWATCH_ADRENALINERUSH = "冲动"
CCWATCH_EVASION = "闪避"
CCWATCH_ROGUESPRINT = "疾跑"
CCWATCH_BLADEFLURRY = "剑刃乱舞"
CCWATCH_CRIPPLINGP = "致残毒药"
CCWATCH_DEADLYP = "致命毒药"

-- Shaman
CCWATCH_FROSTSHOCK = "冰霜震击"
CCWATCH_FLAMESHOCK = "烈焰震击"
CCWATCH_FROSTBRANDWEAPON = "冰封武器"
CCWATCH_STORMSTRIKE = "风暴打击"

-- Miscellaneous
CCWATCH_WARSTOMP = "战争践踏"
CCWATCH_SLEEP = "睡眠"
CCWATCH_NETOMATIC = "撒网器"
CCWATCH_ROCKETHELM = "高爆炸弹"

CCWATCH_WOTF = "亡灵意志"
CCWATCH_PERCEPTION = "感知"

CCWATCH_RANK = "等级"
CCWATCH_DETECTED = "已检测到"
CCWATCH_NOTDETECTED = "未检测到"

CCWATCH_ENABLED = "CCWatch 启用"
CCWATCH_DISABLED = "CCWatch 禁用"

CCWATCH_LOCKED = "CCWatch 锁定"
CCWATCH_UNLOCKED = "CCWatch 解锁"

CCWATCH_INVERSION_ON = "CCWatch 反向开启"
CCWATCH_INVERSION_OFF = "CCWatch 反向关闭"

CCWATCH_STYLE_CURRENT = "仅监视当前目标"
CCWATCH_STYLE_RECENT = "监视近期目标"
CCWATCH_STYLE_ALL = "监视所有目标"

CCWATCH_GROW_OFF = "CCWatch 监视条不增加"
CCWATCH_GROW_UP = "CCWatch 监视条向上增加"
CCWATCH_GROW_DOWN = "CCWatch 监视条向下增加"

CCWATCH_TIMERS_OFF = "计时器关闭"
CCWATCH_TIMERS_ON = "计时器开启"
CCWATCH_TIMERS_REVERSE = "计时器倒计时"

CCWATCH_ARCANIST_ON = "奥术师套装效果可用(+15秒到 "..CCWATCH_POLYMORPH.." 魔法)"
CCWATCH_ARCANIST_OFF = "奥术师套装效果禁用"

CCWATCH_COLOROVERTIME_ON = "监视条颜色随时间渐变开启"
CCWATCH_COLOROVERTIME_OFF = "监视条颜色随时间渐变关闭"
CCWATCH_LEADINGTIMER_ON = "计时器位置: 靠左"
CCWATCH_LEADINGTIMER_OFF = "计时器位置：靠右"
CCWATCH_WARNCC_SETTO = "提醒信息的输出设置为："
CCWATCH_WARNCC_CUSTOM = "自定义提醒信息频道生效：(标准的提醒信息频道 EMOTE, SAY, PARTY, RAID, YELL): "
CCWATCH_WARN_DISABLED = "提醒信息关闭"
CCWATCH_WARN_ENABLED = "提醒信息开启"

CCWATCH_SCALE = "CCWatch 比例设置为 "

CCWATCH_WIDTH = "CCWatch 宽度设置为 "

CCWATCH_ALPHA = "CCWatch 透明度设置为 "

CCWATCH_LOADED = " 已载入 - /ccw"

CCWATCH_HELP1  = " : 使用 - /ccw 指令"
CCWATCH_HELP2  = "指令："
CCWATCH_HELP3  = " on     : 启用 CCWatch"
CCWATCH_HELP4  = " off    : 禁用 CCWatch"
CCWATCH_HELP5  = " lock   : 锁定 CCWatch 并启用"
CCWATCH_HELP6  = " unlock : 解锁 CCWatch 使可移动"
CCWATCH_HELP7  = " u      : 更新升级的技能等级"
CCWATCH_HELP8 = " print  : 列出目前配置"
CCWATCH_HELP9 = " invert : 将监视条反向"
CCWATCH_HELP10 = " scale  : 定义 CCWatch 比例, 从 0.25 到 3.0"
CCWATCH_HELP11 = " width  : 设置监视条宽度, 从 50 到 300"
CCWATCH_HELP12 = " alpha  : 设置监视条透明度, 从 0 到 1"
CCWATCH_HELP13 = " grow   : 设置监视条增加关闭、向上或向下"
CCWATCH_HELP14 = " config : 显示配置窗口"
CCWATCH_HELP15 = " timers : 设置计时器显示关闭，开启或倒计时。有效参数为off, on 和 rev。"
CCWATCH_HELP16 = " warn   : 开始/关闭 提醒信息"
CCWATCH_HELP17 = " warncc : 设置提醒信息使用的频道(EMOTE, SAY, PARTY, RAID, YELL 或自定义)"
