--[[
Name: Babble-Herbs-2.2
Revision: $Rev: 25632 $
Authors(s): kagaro (sal.scotto@gmail.com)
Website: www.wowace.com
Documentation: http://www.wowace.com/wiki/Babble-Herbs-2.2
SVN: http://svn.wowace.com/root/branch/Babble-2.2/Babble-Herbs-2.2
Dependencies: AceLibrary, AceLocale-2.2
License: MIT
]]

local MAJOR_VERSION = "Babble-Herbs-2.2"
local MINOR_VERSION = tonumber(string.sub("$Revision: 25632 $", 12, -3))

if not AceLibrary then error(MAJOR_VERSION .. " requires AceLibrary") end
if not AceLibrary:HasInstance("AceLocale-2.2") then error(MAJOR_VERSION .. " requires AceLocale-2.2") end

local _, x = AceLibrary("AceLocale-2.2"):GetLibraryVersion()
MINOR_VERSION = MINOR_VERSION * 100000 + x

if not AceLibrary:IsNewVersion(MAJOR_VERSION, MINOR_VERSION) then return end

local BabbleHerbs = AceLibrary("AceLocale-2.2"):new(MAJOR_VERSION)

local herbSkills = {}

BabbleHerbs:RegisterTranslations("enUS", function() return {
	["Peacebloom"] = true,
	["Silverleaf"] = true,
	["Earthroot"] = true,
	["Mageroyal"] = true,
	["Briarthorn"] = true,
	["Swiftthistle"] = true,
	["Stranglekelp"] = true,
	["Bruiseweed"] = true,
	["Wild Steelbloom"] = true,
	["Grave Moss"] = true,
	["Kingsblood"] = true,
	["Liferoot"] = true,
	["Fadeleaf"] = true,
	["Goldthorn"] = true,
	["Khadgar's Whisker"] = true,
	["Wintersbite"] = true,
	["Firebloom"] = true,
	["Purple Lotus"] = true,
	["Wildvine"] = true,
	["Arthas' Tears"] = true,
	["Sungrass"] = true,
	["Blindweed"] = true,
	["Ghost Mushroom"] = true,
	["Gromsblood"] = true,
	["Golden Sansam"] = true,
	["Dreamfoil"] = true,
	["Mountain Silversage"] = true,
	["Plaguebloom"] = true,
	["Icecap"] = true,
	["Bloodvine"] = true,
	["Black Lotus"] = true,
	["Felweed"] = true,
	["Dreaming Glory"] = true,
	["Terocone"] = true,
	["Ancient Lichen"] = true,
	["Blood Thistle"] = true,
	["Mana Thistle"] = true,
	["Netherbloom"] = true,
	["Nightmare Vine"] = true,
	["Ragveil"] = true,
	["Flame Cap"] = true,
	["Fel Lotus"] = true,
	
} end)

BabbleHerbs:RegisterTranslations("zhCN", function() return {
	["Peacebloom"] = "\229\174\129\231\165\158\232\138\177",
	["Silverleaf"] = "\233\147\182\229\143\182\232\141\137",
	["Earthroot"] = "\229\156\176\230\160\185\232\141\137",
	["Mageroyal"] = "\233\173\148\231\154\135\232\141\137",
	["Briarthorn"] = "\231\159\179\229\141\151\232\141\137",
	["Swiftthistle"] = "\233\155\168\231\135\149\232\141\137",
	["Stranglekelp"] = "\232\141\134\230\163\152\232\151\187",
	["Bruiseweed"] = "\232\183\140\230\137\147\232\141\137",
	["Wild Steelbloom"] = "\233\135\142\233\146\162\232\138\177",
	["Grave Moss"] = "\229\162\147\229\156\176\232\139\148",
	["Kingsblood"] = "\231\154\135\232\161\128\232\141\137",
	["Liferoot"] = "\230\180\187\230\160\185\232\141\137",
	["Fadeleaf"] = "\230\158\175\229\143\182\232\141\137",
	["Goldthorn"] = "\233\135\145\230\163\152\232\141\137",
	["Khadgar's Whisker"] = "\229\141\161\229\190\183\229\138\160\231\154\132\232\131\161\233\161\187",
	["Wintersbite"] = "\229\134\172\229\136\186\232\141\137",
	["Firebloom"] = "\231\129\171\231\132\176\232\138\177",
	["Purple Lotus"] = "\231\180\171\232\142\178\232\138\177",
	["Wildvine"] = "\233\135\142\232\145\161\232\144\132\232\151\164",
	["Arthas' Tears"] = "\233\152\191\229\176\148\232\144\168\230\150\175\228\185\139\230\179\170",
	["Sungrass"] = "\229\164\170\233\152\179\232\141\137",
	["Blindweed"] = "\231\155\178\231\155\174\232\141\137",
	["Ghost Mushroom"] = "\229\185\189\231\129\181\232\143\135",
	["Gromsblood"] = "\230\160\188\231\189\151\229\167\134\228\185\139\232\161\128",
	["Golden Sansam"] = "\233\187\132\233\135\145\229\143\130",
	["Dreamfoil"] = "\230\162\166\229\143\182\232\141\137",
	["Mountain Silversage"] = "\229\177\177\233\188\160\232\141\137",
	["Plaguebloom"] = "\231\152\159\231\150\171\232\138\177",
	["Icecap"] = "\229\134\176\231\155\150\232\141\137",
	["Bloodvine"] = "\232\161\128\232\151\164",
	["Black Lotus"] = "\233\187\145\232\142\178\232\138\177",
	["Felweed"] = "Felweed",
	["Dreaming Glory"] = "Dreaming Glory",
	["Terocone"] = "Terocone",
	["Ancient Lichen"] = "Ancient Lichen",
	["Blood Thistle"] = "Blood Thistle",
	["Mana Thistle"] = "Mana Thistle",
	["Netherbloom"] = "Netherbloom",
	["Nightmare Vine"] = "Nightmare Vine",
	["Ragveil"] = "Ragveil",
	["Flame Cap"] = "Flame Cap",
	["Fel Lotus"] = "Fel Lotus",
	
} end)


BabbleHerbs:RegisterTranslations("koKR", function() return {
	["Peacebloom"] 			= "평온초",
	["Silverleaf"] 			= "은엽수잎",
	["Earthroot"] 			= "뱀뿌리",
	["Mageroyal"] 			= "마법초",
	["Briarthorn"] 			= "찔레가시",
	["Swiftthistle"] 		= "토끼엉겅퀴풀",
	["Stranglekelp"] 		= "갈래물풀",
	["Bruiseweed"] 			= "생채기풀",
	["Wild Steelbloom"] 		= "야생 철쭉",
	["Grave Moss"] 			= "무덤이끼",
	["Kingsblood"] 			= "왕꽃잎풀",
	["Liferoot"] 			= "생명의 뿌리",
	["Fadeleaf"] 			= "미명초잎",
	["Goldthorn"] 			= "황금가시",
	["Khadgar's Whisker"] 		= "카드가의 수염",
	["Wintersbite"] 		= "겨울서리풀",
	["Firebloom"] 			= "화염초",
	["Purple Lotus"] 		= "보라 연꽃",
	["Wildvine"] 			= "야생덩굴",
	["Arthas' Tears"] 		= "아서스의 눈물",
	["Sungrass"] 			= "태양풀",
	["Blindweed"] 			= "실명초",
	["Ghost Mushroom"] 		= "유령버섯",
	["Gromsblood"] 			= "그롬의 피",
	["Golden Sansam"] 		= "황금 산삼",
	["Dreamfoil"] 			= "꿈풀",
	["Mountain Silversage"] 	= "은초롱이",
	["Plaguebloom"] 		= "역병초",
	["Icecap"] 			= "얼음송이",
	["Bloodvine"] 			= "붉은덩굴",
	["Black Lotus"] 		= "검은 연꽃",
	["Felweed"] 			= "지옥풀",
	["Dreaming Glory"] 		= "꿈초롱이",
	["Terocone"] 			= "테로열매",
	["Ancient Lichen"] 		= "고대 이끼",
	["Blood Thistle"] 		= "피 엉겅퀴",
	["Mana Thistle"] 		= "마나 엉겅퀴",
	["Netherbloom"] 		= "황천꽃", --check
	["Nightmare Vine"] 		= "악몽의 덩굴",
	["Ragveil"] 			= "가림막이버섯", --check
	["Flame Cap"] 			= "불꽃송이", --check
	["Fel Lotus"] 			= "지옥 연꽃", --check
	
} end)

BabbleHerbs:RegisterTranslations("deDE", function() return {
	["Peacebloom"] = "Friedensblume",
	["Silverleaf"] = "Silberblatt",
	["Earthroot"] = "Erdwurzel",
	["Mageroyal"] = "Maguskönigskraut",
	["Briarthorn"] = "Wilddornrose",
	["Swiftthistle"] = "Flitzdistel",
	["Stranglekelp"] = "Würgetang",
	["Bruiseweed"] = "Beulengras",
	["Wild Steelbloom"] = "Wildstahlblume",
	["Grave Moss"] = "Grabmoos",
	["Kingsblood"] = "Königsblut",
	["Liferoot"] = "Lebenswurz",
	["Fadeleaf"] = "Blassblatt",
	["Goldthorn"] = "Golddorn",
	["Khadgar's Whisker"] = "Khadgars Schnurrbart",
	["Wintersbite"] = "Winterbiss",
	["Firebloom"] = "Feuerblüte",
	["Purple Lotus"] = "Lila Lotus",
	["Wildvine"] = "Wildranke",
	["Arthas' Tears"] = "Arthas' Tränen",
	["Sungrass"] = "Sonnengras",
	["Blindweed"] = "Blindkraut",
	["Ghost Mushroom"] = "Geisterpilz",
	["Gromsblood"] = "Gromsblut",
	["Golden Sansam"] = "Goldener Sansam",
	["Dreamfoil"] = "Traumblatt",
	["Mountain Silversage"] = "Bergsilberweisling",
	["Plaguebloom"] = "Pestblüte",
	["Icecap"] = "Eiskappe",
	["Bloodvine"] = "Blutrebe",
	["Black Lotus"] = "Schwarzer Lotus",
  	["Felweed"] = "Teufelsgras",
  	["Dreaming Glory"] = "Traumwinde",
  	["Terocone"] = "Terozapfen",
  	["Ancient Lichen"] = "Urflechte",
  	["Blood Thistle"] = "Blutdistel",
  	["Mana Thistle"] = "Manadistel",
  	["Netherbloom"] = "Netherblüte",
  	["Nightmare Vine"] = "Alptraumranke",
  	["Ragveil"] = "Zottelkappe",
  	["Flame Cap"] = "Flammenkappe",
  	["Fel Lotus"] = "Teufelslotus",
} end)

BabbleHerbs:RegisterTranslations("frFR", function() return {
	["Peacebloom"] = "Feuillargent",
	["Silverleaf"] = "Pacifique",
	["Earthroot"] = "Terrestrine",
	["Mageroyal"] = "Mage royal",
	["Briarthorn"] = "Eglantine",
	["Swiftthistle"] = "Chardonnier",
	["Stranglekelp"] = "Etouffante",
	["Bruiseweed"] = "Doulourante",
	["Wild Steelbloom"] = "Aciérite sauvage",
	["Grave Moss"] = "Tombeline",
	["Kingsblood"] = "Sang-royal",
	["Liferoot"] = "Vietérule",
	["Fadeleaf"] = "Pâlerette",
	["Goldthorn"] = "Dorépine",
	["Khadgar's Whisker"] = "Moustache de Khadgar",
	["Wintersbite"] = "Hivernale",
	["Firebloom"] = "Fleur de feu",
	["Purple Lotus"] = "Lotus pourpre",
	["Wildvine"] = "Sauvageonne",
	["Arthas' Tears"] = "Larmes d'Arthas",
	["Sungrass"] = "Soleillette",
	["Blindweed"] = "Aveuglette",
	["Ghost Mushroom"] = "Champignon fantôme",
	["Gromsblood"] = "Gromsang",
	["Golden Sansam"] = "Sansam doré",
	["Dreamfoil"] = "Feuillerêve",
	["Mountain Silversage"] = "Sauge-argent des montagnes",
	["Plaguebloom"] = "Fleur de peste",
	["Icecap"] = "Calot de glace",
	["Bloodvine"] = "Vignesang",
	["Black Lotus"] = "Lotus noir",
	["Felweed"] = "Gangrelette",
	["Dreaming Glory"] = "Glaurier",
	["Terocone"] = "Terocône",
	["Ancient Lichen"] = "Lichen ancien",
	["Blood Thistle"] = "Chardon sanglant",
	["Mana Thistle"] = "Chardon de mana",
	["Netherbloom"] = "Néantine",
	["Nightmare Vine"] = "Cauchemardelle",
	["Ragveil"] = "Voile-misère",
	["Flame Cap"] = "Chapeflamme",
	["Fel Lotus"] = "Gangrelotus",
} end)

BabbleHerbs:RegisterTranslations("esES", function() return {
	["Silverleaf"] = "Hojaplata",
	["Peacebloom"] = "Flor de paz",
	["Mageroyal"] = "Marregal",
	["Bruiseweed"] = "Hierba cardenal",
	["Kingsblood"] = "Sangrerregia",
	["Fadeleaf"] = "P\195\161lida",
	["Stranglekelp"] = "Alga estranguladora",
	["Liferoot"] = "Vidarra\195\173z",
	["Briarthorn"] = "Brezospina",
	["Earthroot"] = "Ra\195\173z de tierra",
	["Sungrass"] = "Solea",
	["Blindweed"] = "Carolina",
	["Gromsblood"] = "Gromsanguina",
	["Dreamfoil"] = "Hojasue\195\177o",
	["Firebloom"] = "Flor de Fuego",
	["Arthas' Tears"] = "L\195\161grimas de Arthas",
	["Purple Lotus"] = "Loto morado",
	["Goldthorn"] = "Espina de oro",
	["Wildvine"] = "Atriplex salvaje",
	["Grave Moss"] = "Moho de tumba",
	["Mountain Silversage"] = "Salviargenta de monta\195\177a",
	["Black Lotus"] = "Loto negro",
	["Ghost Mushroom"] = "Champi\195\177\195\179n fantasma",
	["Golden Sansam"] = "Sansam dorado",
	["Icecap"] = "Setelo",
	["Khadgar's Whisker"] = "Mostacho de Khadgar",
	["Plaguebloom"] = "Flor de peste",
	["Swiftthistle"] = "Cardoveloz",
	["Wild Steelbloom"] = "Ac\195\169rita salvaje",
	["Wintersbite"] = "Ivernalia",
	--["Felweed"] = true,
	--["Dreaming Glory"] = true,
	--["Terocone"] = true,
	--["Ancient Lichen"] = true,
	--["Blood Thistle"] = true,
	--["Mana Thistle"] = true,
	--["Netherbloom"] = true,
	--["Nightmare Vine"] = true,
	--["Ragveil"] = true,
	--["Flame Cap"] = true,
	--["Fel Lotus"] = true,
} end)

BabbleHerbs:RegisterTranslations("zhTW", function() return {
	["Silverleaf"] = "銀葉草",
	["Peacebloom"] = "寧神花",
	["Mageroyal"] = "魔皇草",
	["Bruiseweed"] = "跌打草",
	["Kingsblood"] = "皇血草",
	["Fadeleaf"] = "枯葉草",
	["Stranglekelp"] = "荊棘藻",
	["Liferoot"] = "活根草",
	["Briarthorn"] = "石南草",
	["Earthroot"] = "地根草",
	["Sungrass"] = "太陽草",
	["Blindweed"] = "盲目草",
	["Gromsblood"] = "格羅姆之血",
	["Dreamfoil"] = "夢葉草",
	["Firebloom"] = "火焰花",
	["Arthas' Tears"] = "阿薩斯之淚",
	["Purple Lotus"] = "紫蓮花",
	["Goldthorn"] = "金棘草",
	["Wildvine"] = "野葡萄藤",
	["Grave Moss"] = "墓地苔",
	["Mountain Silversage"] = "山鼠草",
	["Black Lotus"] = "黑蓮花",
	["Ghost Mushroom"] = "幽靈菇",
	["Golden Sansam"] = "黃金蔘",
	["Icecap"] = "冰蓋草",
	["Khadgar's Whisker"] = "卡德加的鬍鬚",
	["Plaguebloom"] = "瘟疫花",
	["Swiftthistle"] = "雨燕草",
	["Wild Steelbloom"] = "野鋼花",
	["Wintersbite"] = "冬刺草",
	--["Felweed"] = true,
	--["Dreaming Glory"] = true,
	--["Terocone"] = true,
	--["Ancient Lichen"] = true,
	--["Blood Thistle"] = true,
	--["Mana Thistle"] = true,
	--["Netherbloom"] = true,
	--["Nightmare Vine"] = true,
	--["Ragveil"] = true,
	--["Flame Cap"] = true,
	--["Fel Lotus"] = true,
} end)

BabbleHerbs:Debug()
BabbleHerbs:SetStrictness(true)

AceLibrary:Register(BabbleHerbs, MAJOR_VERSION, MINOR_VERSION)
BabbleHerbs = nil
