if (GetLocale() == "zhCN") then

-----------------------
-- Localised Globals --
-----------------------
ATLASLOOT_FIRST_TIME_TEXT = "欢迎使用 Atlasloot Enhanced.  请在选项里设置一下插件提示方式以及聊天窗口物品链接方式.\n\n  你可以随时通过'/atlasloot'命令打开此选项窗口.";
ATLASLOOT_FIRST_TIME_BUTTON = "选项";

ATLASLOOT_OLD_ATLAS_TEXT_PT1 = "检测到你的 Atlas 版本与此版 Atlasloot 不匹配 (";
ATLASLOOT_OLD_ATLAS_TEXT_PT2 = ").  这可能会导致发生错误, 请到 http://www.atlasmod.com 下载 Atlas 最新版本.";
ATLASLOOT_OLD_ATLAS_BUTTON = "确定";


ATLASLOOT_DROP_RATE = "掉落率: ";
ATLASLOOT_DKP = "DKP";
ATLASLOOT_BANNER_TEXT = "点击BOSS名称查看."

ATLASLOOT_ERRORTOOLTIP_L1 = "未知物品";
ATLASLOOT_ERRORTOOLTIP_L2 = "物品ID:";
ATLASLOOT_ERRORTOOLTIP_L3 = "此物品属于未知物品.\n查看此物品很可能引起游戏断开.你需要首先在游戏里见过它.\n这个问题来自Blizzard魔兽世界补丁1.10的限制措施 .";
ATLASLOOT_ERRORTOOLTIP_L4 = "你可以右键单击此物品向服务器查询.\n注意：可能引起游戏断开.";

ATLASLOOT_SAFE_MESSAGE = "现在物品链接是安全的";
ATLASLOOT_QUERY_MESSAGE = "正在向服务器查询";
ATLASLOOT_RECLICK_MESSAGE = ".  请再次右键点击此物品，直到这条消息不再出现.";

ATLASLOOT_UIBACK = "返回";

ATLASLOOT_CLOTH = "布甲";
ATLASLOOT_LEATHER = "皮甲";
ATLASLOOT_MAIL = "锁甲";
ATLASLOOT_PLATE = "板甲";

ATLASLOOT_HEAD = "头部";
ATLASLOOT_NECK = "颈部";
ATLASLOOT_SHOULDER = "肩部";
ATLASLOOT_BACK = "背部";
ATLASLOOT_CHEST = "胸部";
ATLASLOOT_SHIRT = "衬衫";
ATLASLOOT_TABARD = "公会徽章";
ATLASLOOT_WRIST = "手腕";
ATLASLOOT_HANDS = "手";
ATLASLOOT_WAIST = "腰部";
ATLASLOOT_LEGS = "腿部";
ATLASLOOT_FEET = "脚";
ATLASLOOT_RING = "手指";
ATLASLOOT_TRINKET = "饰品";
ATLASLOOT_OFF_HAND = "副手物品";
ATLASLOOT_RELIC = "圣物";

ATLASLOOT_WEAPONS = "武器";
ATLASLOOT_ONE_HAND = "单手";
ATLASLOOT_TWO_HAND = "双手";
ATLASLOOT_MAIN_HAND = "主手";
ATLASLOOT_OFFHAND = "副手";

ATLASLOOT_AXE = "斧";
ATLASLOOT_BOW = "弓";
ATLASLOOT_CROSSBOW = "弩";
ATLASLOOT_DAGGER = "匕首";
ATLASLOOT_GUN = "枪械";
ATLASLOOT_MACE = "锤";
ATLASLOOT_POLEARM = "长柄武器";
ATLASLOOT_SHIELD = "盾牌";
ATLASLOOT_STAFF = "法杖";
ATLASLOOT_SWORD = "剑";
ATLASLOOT_THROWN = "投掷武器";
ATLASLOOT_WAND = "魔杖";
ATLASLOOT_FIST = "拳套";

ATLASLOOT_POTION = "药剂";
ATLASLOOT_FOOD = "食物";
ATLASLOOT_DRINK = "饮料";
ATLASLOOT_BANDAGE = "绷带";
ATLASLOOT_ARROW = "箭";
ATLASLOOT_BULLET = "子弹"
ATLASLOOT_MOUNT = "坐骑";
ATLASLOOT_AMMO = "弹药袋";
ATLASLOOT_QUIVER = "箭袋";
ATLASLOOT_BAG = "容器";
ATLASLOOT_ENCHANT = "附魔";
ATLASLOOT_TRADE_GOODS = "商品";
ATLASLOOT_SCOPE = "瞄准镜";
ATLASLOOT_KEY = "钥匙";
ATLASLOOT_PET = "宠物";
ATLASLOOT_IDOL = "神像";
ATLASLOOT_TOTEM = "图腾";
ATLASLOOT_LIBRAM = "圣契";
ATLASLOOT_DARKMOON = "暗月套牌";
ATLASLOOT_BOOK = "书籍";
ATLASLOOT_BANNER = "军旗";

ATLASLOOT_DRUID = "德鲁伊";
ATLASLOOT_HUNTER = "猎人";
ATLASLOOT_MAGE = "法师";
ATLASLOOT_PALADIN = "圣骑士";
ATLASLOOT_PRIEST = "牧师";
ATLASLOOT_ROGUE = "盗贼";
ATLASLOOT_SHAMAN = "萨满祭司";
ATLASLOOT_WARLOCK = "术士";
ATLASLOOT_WARRIOR = "战士";

ATLASLOOT_ALCHEMY = "炼金";
ATLASLOOT_BLACKSMITHING = "锻造";
ATLASLOOT_COOKING = "烹饪";
ATLASLOOT_ENCHANTING = "附魔";
ATLASLOOT_ENGINEERING = "工程";

ATLASLOOT_FIRST_AID = "急救";
ATLASLOOT_LEATHERWORKING = "制皮";
ATLASLOOT_TAILORING = "裁缝";
ATLASLOOT_DRAGONSCALE = "龙鳞制皮";
ATLASLOOT_TRIBAL = "部族制皮";
ATLASLOOT_ELEMENTAL = "元素制皮";
ATLASLOOT_JEWELCRAFTING = "宝石工艺";

ATLASLOOT_NEUTRAL = "中立";
ATLASLOOT_FRIENDLY = "友善";
ATLASLOOT_HONORED = "尊敬";
ATLASLOOT_REVERED = "崇敬";
ATLASLOOT_EXALTED = "崇拜";

ATLASLOOT_CLASSES = "职业：";
ATLASLOOT_QUEST1 = "该物品将触发一个任务";
ATLASLOOT_QUEST2 = "任务物品";
ATLASLOOT_QUEST3 = "任务奖励";
ATLASLOOT_SHARED = "共同掉落";
ATLASLOOT_HORDE = "部落";
ATLASLOOT_ALLIANCE = "联盟";
ATLASLOOT_UNIQUE = "唯一";
ATLASLOOT_RIGHTSIDE = "右半部分";
ATLASLOOT_LEFTSIDE = "左半部分";
ATLASLOOT_FELCOREBAG = "28格灵魂包";
ATLASLOOT_ONYBAG = "18格";
ATLASLOOT_WCBAG = "10格";
ATLASLOOT_FULLSKILL = "(300)";
ATLASLOOT_295 = "(295)";
ATLASLOOT_275 = "(275)";
ATLASLOOT_265 = "(265)";
ATLASLOOT_290 = "(290)";
ATLASLOOT_SET = "套装";
ATLASLOOT_285 = "(285)";
ATLASLOOT_16SLOT = "16格";

ATLASLOOT_VIPERSET = "S) 套装: 毒蛇的拥抱 (5件套)";
ATLASLOOT_COBRAHN = "考布莱恩 掉落";
ATLASLOOT_ANACONDRA = "安娜科德拉 掉落";
ATLASLOOT_SERPENTIS = "瑟芬迪斯 掉落";
ATLASLOOT_FANGDRUID = "尖牙德鲁伊 掉落";
ATLASLOOT_PYTHAS = "皮萨斯 掉落";

ATLASLOOT_DEFIASSET = "S) 套装: 黑暗迪菲亚护甲 (5件套)";
ATLASLOOT_VANCLEEF = "艾德温·范克里夫 掉落";
ATLASLOOT_GREENSKIN = "绿皮队长 掉落";
ATLASLOOT_DEFIASMINER = "迪菲亚赤膊矿工 掉落";
ATLASLOOT_DEFIASOVERSEER = "迪菲亚监工/迪菲亚工头 掉落";

ATLASLOOT_Primal_Hakkari_Kossack = "原始哈卡莱套索";
ATLASLOOT_Primal_Hakkari_Shawl = "原始哈卡莱披肩";
ATLASLOOT_Primal_Hakkari_Bindings = "原始哈卡莱护腕";
ATLASLOOT_Primal_Hakkari_Sash = "原始哈卡莱腰带";
ATLASLOOT_Primal_Hakkari_Stanchion = "原始哈卡莱直柱";
ATLASLOOT_Primal_Hakkari_Aegis = "原始哈卡莱之盾";
ATLASLOOT_Primal_Hakkari_Girdle = "原始哈卡莱束带";
ATLASLOOT_Primal_Hakkari_Armsplint = "原始哈卡莱护臂";
ATLASLOOT_Primal_Hakkari_Tabard = "原始哈卡莱徽章";

ATLASLOOT_Qiraji_Ornate_Hilt = "其拉装饰刀柄";
ATLASLOOT_Qiraji_Martial_Drape = "其拉军用披风";
ATLASLOOT_Qiraji_Magisterial_Ring = "其拉将领戒指";
ATLASLOOT_Qiraji_Ceremonial_Ring = "其拉典礼戒指";
ATLASLOOT_Qiraji_Regal_Drape = "其拉帝王披风";
ATLASLOOT_Qiraji_Spiked_Hilt = "其拉尖刺刀柄";

ATLASLOOT_Qiraji_Bindings_of_Dominance = "其拉统御腕轮";
ATLASLOOT_Veknilashs_Circlet = "维克尼拉斯的头饰";
ATLASLOOT_Ouros_Intact_Hide = "奥罗的外皮";
ATLASLOOT_Husk_of_the_Old_God = "上古之神的外鞘";
ATLASLOOT_Qiraji_Bindings_of_Command = "其拉命令腕轮";
ATLASLOOT_Veklors_Diadem = "维克洛尔的王冠";
ATLASLOOT_Skin_of_the_Great_Sandworm = "巨型沙虫的皮";
ATLASLOOT_Carapace_of_the_Old_God = "上古之神的甲壳";

ATLASLOOT_SCARLETSET = "S) 套装: 血色十字军链甲 (6件套)";
ATLASLOOT_SCARLETDEFENDER = "血色防御者/血色仆从 掉落";
ATLASLOOT_SCARLETTRASH = "小怪掉落";
ATLASLOOT_SCARLETCHAMPION = "血色勇士 掉落";
ATLASLOOT_SCARLETCENTURION = "血色百夫长 掉落";
ATLASLOOT_SCARLETHEROD = "  赫洛德/莫格莱尼 掉落";
ATLASLOOT_SCARLETPROTECTOR = "血色保卫者/血色卫兵 掉落"; 
ATLASLOOT_SCARLETINTERROGATOR = "审讯员韦沙斯";

ATLASLOOT_AQ40_SETS="安其拉神殿职业套装";
ATLASLOOT_AQ20_SETS="安其拉废墟职业套装";
ATLASLOOT_ZG_SETS="祖尔格拉布职业套装";
ATLASLOOT_TIER0_SETS="T0 套装";
ATLASLOOT_TIER05_SETS="T0.5 套装";
ATLASLOOT_TIER1_SETS="T1 套装";
ATLASLOOT_TIER2_SETS="T2 套装";
ATLASLOOT_TIER3_SETS="T3 套装";
ATLASLOOT_PVP_SETS="PvP 套装";

ATLASLOOT_ZG_DRUID="占卜师套装";
ATLASLOOT_ZG_HUNTER="捕猎者套装";
ATLASLOOT_ZG_MAGE="幻术师套装";
ATLASLOOT_ZG_PALADIN="思考者护甲";
ATLASLOOT_ZG_PRIEST="忏悔者衣饰";
ATLASLOOT_ZG_ROGUE="狂妄者衣饰";
ATLASLOOT_ZG_SHAMAN="预言者套装";
ATLASLOOT_ZG_WARLOCK="恶魔师护甲";
ATLASLOOT_ZG_WARRIOR="辩护者重甲";

ATLASLOOT_AQ20_DRUID="不灭的生命";
ATLASLOOT_AQ20_HUNTER="隐秘的通途";
ATLASLOOT_AQ20_MAGE="魔法的秘密";
ATLASLOOT_AQ20_PALADIN="永恒的公正";
ATLASLOOT_AQ20_PRIEST="无尽的智慧";
ATLASLOOT_AQ20_ROGUE="笼罩之阴影";
ATLASLOOT_AQ20_SHAMAN="聚集的风暴";
ATLASLOOT_AQ20_WARLOCK="禁断的邪语";
ATLASLOOT_AQ20_WARRIOR="坚定的力量";

ATLASLOOT_AQ40_DRUID="起源套装";
ATLASLOOT_AQ40_HUNTER="攻击者";
ATLASLOOT_AQ40_MAGE="神秘套装";
ATLASLOOT_AQ40_PALADIN="复仇者";
ATLASLOOT_AQ40_PRIEST="神谕者";
ATLASLOOT_AQ40_ROGUE="死亡执行者的拥抱";
ATLASLOOT_AQ40_SHAMAN="风暴召唤者";
ATLASLOOT_AQ40_WARLOCK="厄运召唤者";
ATLASLOOT_AQ40_WARRIOR="征服者";

ATLASLOOT_T0_DRUID = "野性之心";
ATLASLOOT_T0_HUNTER = "野兽追猎者";
ATLASLOOT_T0_MAGE = "博学者的徽记";
ATLASLOOT_T0_PALADIN = "光铸护甲";
ATLASLOOT_T0_PRIEST = "虔诚";
ATLASLOOT_T0_ROGUE = "迅影";
ATLASLOOT_T0_SHAMAN = "元素";
ATLASLOOT_T0_WARLOCK = "鬼雾";
ATLASLOOT_T0_WARRIOR = "勇气";

ATLASLOOT_T05_DRUID = "狂野之心";
ATLASLOOT_T05_HUNTER = "兽王";
ATLASLOOT_T05_MAGE = "巫师";
ATLASLOOT_T05_PALADIN = "魂铸";
ATLASLOOT_T05_PRIEST = "坚贞";
ATLASLOOT_T05_ROGUE = "暗幕";
ATLASLOOT_T05_SHAMAN = "五雷";
ATLASLOOT_T05_WARLOCK = "死雾";
ATLASLOOT_T05_WARRIOR = "英勇";

ATLASLOOT_T1_DRUID = "塞纳里奥";
ATLASLOOT_T1_HUNTER = "巨人追猎者";
ATLASLOOT_T1_MAGE = "奥术师";
ATLASLOOT_T1_PALADIN = "秩序之源";
ATLASLOOT_T1_PRIEST = "预言";
ATLASLOOT_T1_ROGUE = "夜幕杀手";
ATLASLOOT_T1_SHAMAN = "大地之怒";
ATLASLOOT_T1_WARLOCK = "恶魔之心";
ATLASLOOT_T1_WARRIOR = "力量";

ATLASLOOT_T2_DRUID = "怒风";
ATLASLOOT_T2_HUNTER = "巨龙追猎者";
ATLASLOOT_T2_MAGE = "灵风";
ATLASLOOT_T2_PALADIN = "审判";
ATLASLOOT_T2_PRIEST = "卓越";
ATLASLOOT_T2_ROGUE = "血牙";
ATLASLOOT_T2_SHAMAN = "无尽风暴";
ATLASLOOT_T2_WARLOCK = "复仇";
ATLASLOOT_T2_WARRIOR = "愤怒";

ATLASLOOT_T3_DRUID = "梦游者";
ATLASLOOT_T3_HUNTER = "地穴追猎者";
ATLASLOOT_T3_MAGE = "霜火";
ATLASLOOT_T3_PALADIN = "救赎";
ATLASLOOT_T3_PRIEST = "信仰";
ATLASLOOT_T3_ROGUE = "骨镰";
ATLASLOOT_T3_SHAMAN = "碎地者";
ATLASLOOT_T3_WARLOCK = "瘟疫之心";
ATLASLOOT_T3_WARRIOR = "无畏";

ATLASLOOT_T3_DRUID="梦游者";
ATLASLOOT_T3_HUNTER="地穴追猎者";
ATLASLOOT_T3_MAGE="霜火";
ATLASLOOT_T3_PALADIN="救赎";
ATLASLOOT_T3_PRIEST="信仰";
ATLASLOOT_T3_ROGUE="骨镰";
ATLASLOOT_T3_SHAMAN="碎地者";
ATLASLOOT_T3_WARLOCK="瘟疫之心";
ATLASLOOT_T3_WARRIOR="无畏";

ATLASLOOT_BROOD_CONQUEROR = "征服者之路";
ATLASLOOT_BROOD_INVOKER = "祈求者之路";
ATLASLOOT_BROOD_PROTECTOR = "保护者之路";

ATLASLOOT_AQ40_CLASS_SET_PIECES_1 = "X) 安其拉神殿职业套装";
ATLASLOOT_AQ40_BROOD_RINGS = "X) 青铜龙声望戒指";
ATLASLOOT_ZG_CLASS_SET_PIECES_1 = "X) 祖尔格拉布职业套装";
ATLASLOOT_AQ20_CLASS_SET_PIECES_1 = "X) 安其拉废墟职业套装";
ATLASLOOT_NAXX_SET_PIECES = "X) T3 套装";
ATLASLOOT_BWL_SET_PIECES = "X) T2 套装";
ATLASLOOT_MC_SET_PIECES = "X) T1 套装";
ATLASLOOT_T0_SET_PIECES = "X) T0 套装";
ATLASLOOT_T05_SET_PIECES = "X) T0.5 套装";
ATLASLOOT_AQ_ENCHANTS = "X) 安其拉附魔公式";
ATLASLOOT_ZG_ENCHANTS = "X) 祖尔格拉布附魔";
ATLASLOOT_CLASS_BOOKS = "X) 职业技能书";
ATLASLOOT_TRIBUTE_RUN = "X) 贡品";
ATLASLOOT_DM_BOOKS = "X) 厄运之槌任务书";
ATLASLOOT_TRASH_MOBS = "X) 小怪掉落";
ATLASLOOT_RANDOM_LOOT = "X) BOSS随机掉落";
ATLASLOOT_CLASS_SET_PIECES = "X) 声望奖励装备";
ATLASLOOT_NO_ITEMINFO = " |cffff0000(未知物品)";

ATLASLOOT_BRDARENA1 = "阿努希尔";
ATLASLOOT_BRDARENA2 = "剜眼者";
ATLASLOOT_BRDARENA3 = "修行者高罗什";
ATLASLOOT_BRDARENA4 = "格里兹尔";
ATLASLOOT_BRDARENA5 = "爬行者赫杜姆";
ATLASLOOT_BRDARENA6 = "破坏者奥科索尔";

ATLASLOOT_OPTIONS_TITLE = "Atlasloot选项";
ATLASLOOT_OPTIONS_SAFE_LINKS = "安全物品链接|cff1eff00（推荐）|r";
ATLASLOOT_OPTIONS_ALL_LINKS = "使用所有链接|cffff0000（可能导致掉线!）|r";
ATLASLOOT_OPTIONS_DEFAULT_TOOLTIPS = "默认提示";
ATLASLOOT_OPTIONS_LOOTLINK_TOOLTIPS = "Lootlink提示|cff1eff00（推荐）|r";
ATLASLOOT_OPTIONS_LOOTLINK_TOOLTIPS_DISABLED = "|cff9d9d9dLootlink提示（推荐）|r";
ATLASLOOT_OPTIONS_ITEMSYNC_TOOLTIPS = "ItemSync提示";
ATLASLOOT_OPTIONS_ITEMSYNC_TOOLTIPS_DISABLED = "|cff9d9d9dItemSync提示|r";
ATLASLOOT_OPTIONS_EQUIPCOMPARE = "使用EquipCompare";
ATLASLOOT_OPTIONS_EQUIPCOMPARE_DISABLED = "|cff9d9d9d使用EquipCompare|r";
ATLASLOOT_OPTIONS_OPAQUE = "查看掉落时不显示背景地图";
ATLASLOOT_OPTIONS_ITEMIDS = "总是显示物品ID";
ATLASLOOT_OPTIONS_DONE = "完成";

-------------------------
----Localised Globals----
-------------------------

ATLASLOOT_BG_FRIENDLY = "X) 友善声望报酬";
ATLASLOOT_BG_HONORED = "X) 尊敬声望报酬";
ATLASLOOT_BG_REVERED = "X) 崇敬声望报酬";
ATLASLOOT_BG_EXALTED = "X) 崇拜声望报酬";

ATLASLOOT_BG_STORMPIKE = "雷矛卫队";
ATLASLOOT_BG_FROSTWOLF = "霜狼氏族";
ATLASLOOT_BG_SENTINELS = "银翼哨兵";
ATLASLOOT_BG_OUTRIDERS = "战歌前锋";
ATLASLOOT_BG_ARATHOR = "阿拉索联军";
ATLASLOOT_BG_DEFILERS = "污染者";

ATLASLOOT_PVP_EPIC_H_DRUID = "督军的圣装";
ATLASLOOT_PVP_EPIC_H_HUNTER = "督军的猎装";
ATLASLOOT_PVP_EPIC_H_MAGE = "督军的法衣";
ATLASLOOT_PVP_EPIC_H_PRIEST = "督军的神服";
ATLASLOOT_PVP_EPIC_H_ROGUE = "督军的制服";
ATLASLOOT_PVP_EPIC_H_SHAMAN = "督军的震撼";
ATLASLOOT_PVP_EPIC_H_WARLOCK = "督军的魔装";
ATLASLOOT_PVP_EPIC_H_WARRIOR = "督军的战甲";

ATLASLOOT_PVP_EPIC_A_DRUID = "元帅的圣装";
ATLASLOOT_PVP_EPIC_A_HUNTER = "元帅的猎装";
ATLASLOOT_PVP_EPIC_A_MAGE = "元帅的法衣";
ATLASLOOT_PVP_EPIC_A_PALADIN = "元帅的庇护";
ATLASLOOT_PVP_EPIC_A_PRIEST = "元帅的神服";
ATLASLOOT_PVP_EPIC_A_ROGUE = "元帅的制服";
ATLASLOOT_PVP_EPIC_A_WARLOCK = "元帅的魔装";
ATLASLOOT_PVP_EPIC_A_WARRIOR = "元帅的战甲";

ATLASLOOT_PVP_RARE_H_DRUID = "勇士的庇护";
ATLASLOOT_PVP_RARE_H_HUNTER = "勇士的职责";
ATLASLOOT_PVP_RARE_H_MAGE = "勇士的秘密";
ATLASLOOT_PVP_RARE_H_PRIEST = "勇士的授权";
ATLASLOOT_PVP_RARE_H_ROGUE = "勇士的护卫";
ATLASLOOT_PVP_RARE_H_SHAMAN = "勇士的风暴";
ATLASLOOT_PVP_RARE_H_WARLOCK = "勇士的鬼纹";
ATLASLOOT_PVP_RARE_H_WARRIOR = "勇士的战铠";

ATLASLOOT_PVP_RARE_A_DRUID = "少校的庇护";
ATLASLOOT_PVP_RARE_A_HUNTER = "少校的职责";
ATLASLOOT_PVP_RARE_A_MAGE = "少校的秘密";
ATLASLOOT_PVP_RARE_A_PALADIN = "少校的壁垒";
ATLASLOOT_PVP_RARE_A_PRIEST = "少校的授权";
ATLASLOOT_PVP_RARE_A_ROGUE = "少校的护卫";
ATLASLOOT_PVP_RARE_A_WARLOCK = "少校的鬼纹";
ATLASLOOT_PVP_RARE_A_WARRIOR = "少校的战铠";

ATLASLOOT_PVP_SET_PIECES = "X) PvP套装";
ATLASLOOT_PVP_SET_PIECES_HEADER = "PvP声望奖励";
ATLASLOOT_PVP_EPIC_SET = "史诗品质套装";
ATLASLOOT_PVP_RARE_SET = "精良品质套装";
ATLASLOOT_LEGENDARIES =  "传说武器";

ATLASLOOT_PANEL_BUTTON_OPTIONS = "选项";
ATLASLOOT_PANEL_BUTTON_SETS = "套装";
ATLASLOOT_PANEL_BUTTON_REPUTATION = "阵营";

ATLASLOOT_FACTION_DARKMOON = "暗月马戏团";
ATLASLOOT_FACTION_THORIUM = "瑟银兄弟会";
ATLASLOOT_FACTION_TIMBERMAW = "木喉要塞";
ATLASLOOT_FACTION_ARGENT = "银色黎明";
ATLASLOOT_FACTION_CENARION = "塞纳里奥议会";
ATLASLOOT_FACTION_BROOD = "诺兹多姆的子嗣";
ATLASLOOT_FACTION_ZANDALAR = "赞达拉部族";
ATLASLOOT_FACTION_CENARION_EXPEDITION = "The Cenarion Expedition";
ATLASLOOT_FACTION_SPOREGGAR = "The Sporeggar";
ATLASLOOT_FACTION_KURENAI = "The Kurenai";
ATLASLOOT_FACTION_ARGENT_INSIGNIAS = "任务换取";
ATLASLOOT_FACTION_ARGENT_TOKEN = "徽记换取"; 

ATLASLOOT_RED_SCEPTER = "红色节杖碎片";
ATLASLOOT_BLUE_SCEPTER = "蓝色节杖碎片";
ATLASLOOT_GREEN_SCEPTER = "绿色节杖碎片";
ATLASLOOT_SCEPTER = "流沙节杖";
ATLASLOOT_AQ_OPENING = "X) 安其拉开门任务奖励";

end