--$Id: deDE.lua 21897 2006-12-23 16:21:41Z chinkuwaila $-- 
-- deDE localization by Gamefaq
local L = AceLibrary("AceLocale-2.2"):new("OneBag")
L:RegisterTranslations("deDE", function()
   return {
      ["Frame"]	= "Fenster",
      ["Frame Options"]	= "Fensteroptionen.",
      ["Columns"]	= "Spalten",
      ["Sets the number of columns to use"]	= "Stellt die Spaltenzahl ein.",
      ["Scale"]	= "Skalierung",
      ["Sets the scale of the frame"]	= "Stellt die Gr\195\182\195\159e des Fensters ein.",
      ["Strata"]	= "Schichten",
      ["Sets the strata of the frame"]	= "Stellt die Schichth\195\182he des Fensters ein, wodurch das \195\188berlagern dieses Fensters mit einem anderen verhindert werden kann.",
      ["Alpha"]	= "Transparenz",
      ["Sets the alpha of the frame"]	= "Stellt die Transparenz des Fensters ein.",
      ["Locked"]	= "Fixieren",
      ["Toggles the ability to move the frame"]	= "Bestimmt, ob das Fenster verschoben werden kann.",
      ["Clamped"]	= "Sichtbereich",
      ["Toggles the ability to drag the frame off screen."]	= "Verhindert, dass das Fenster au\195\159erhalb des sichtbaren Bereichs geschoben wird.",
      ["Bag Break"] = "Taschen in neuer Zeile",
      ["Sets wether to start a new row at the beginning of a bag."] = "Die Anzeige jeder Tasche in einer neuen Zeile beginnen.",
      ["Vertical Alignment"] = "Vertikale Ausrichtung",
      ["Sets wether to have the extra spaces on the top or bottom."] = "Freie Taschenpl\195\164tze oben oder unten anzeigen.",
      ["Top"] = "Oben",
      ["Bottom"] = "Unten",

      ["Show"]	= "Zeige",
      ["Various Display Options"]	= "Verschiedene Anzeigeoptionen.",
      ["Counts"]	= "Anzahl",
      ["Toggles showing the counts for special bags."]	= "Anzahl freier Pl\195\164tze in den Spezialtaschen anzeigen.",
      ["Direction"]	= "Richtung",
      ["Forward"]	= "Vorw\195\164rts",
      ["Toggles direction the bags are shown"]	= "Bestimmt die Richtung, in der die Taschen angezeigt werden.",
      ["|cffff0000Reverse|r"]	= "|cffff0000R\195\188ckw\195\164rts|r",
      ["|cff00ff00Forward|r"]	= "|cffff0000Vorw\195\164rts|r",
      ["Ammo Bag"]	= "Munitionstaschen",
      ["Turns display of ammo bags on and off."]	= "Schaltet die Munitionstaschen an und aus.",
      ["Soul Bag"]	= "Seelentaschen",
      ["Turns display of soul bags on and off."]	= "Schaltet die Seelentaschen an und aus.",
      ["Profession Bag"]	= "Berufe-Taschen",
      ["Turns display of profession bags on and off."]	= "Schaltet die Berufe-Taschen an und aus.",
      ["Backpack"] = "Rucksack",
      ["Turns display of your backpack on and off."] = "Schaltet den Rucksack an und aus.",
      ["First Bag"] = "Erste Tasche",
      ["Turns display of your first bag on and off."] = "Schaltet die Anzeige der ersten Tasche an und aus.",
      ["Second Bag"] = "Zweite Tasche",
      ["Turns display of your second bag on and off."] = "Schaltet die Anzeige der zweiten Tasche an und aus.",
      ["Third Bag"] = "Dritte Tasche",
      ["Turns display of your third bag on and off."] = "Schaltet die Anzeige der dritten Tasche an und aus.",
      ["Fourth Bag"] = "Vierte Tasche",
      ["Turns display of your fourth bag on and off."] = "Schaltet die Anzeige der vierte Tasche an und aus.",
      ["'s Bags"] = "s Taschen",		

      ["Colors"]	= "Farben",
      ["Different color code settings."]	= "Verschiedene Farbeinstellungen.",
      ["Mouseover Color"]	= "Hervorhebungsfarbe",
      ["Changes the highlight color for when you mouseover a bag slot."]	= "Ver\195\164ndert die Farbe, in der Taschenpl\195\164tze hervorgehoben werden, wenn du mit dem Mauszeiger darauf zeigst.",
      ["Ammo Bag Color"]	= "Farbe der Munitionstaschen",
      ["Changes the highlight color for Ammo Bags."]	= "Ver\195\164ndert die Hervorhebungsfarbe f\195\188r Munitionstaschen.",
      ["Soul Bag Color"]	= "Farbe der Seelentaschen",
      ["Changes the highlight color for Soul Bags."]	= "Ver\195\164ndert die Hervorhebungsfarbe f\195\188r Seelentaschen.",
      ["Profession Bag Color"]	= "Farbe der Berufe-Taschen",
      ["Changes the highlight color for Profession Bags."]	= "Ver\195\164ndert die Hervorhebungsfarbe f\195\188r Berufe-Taschen.",
      ["Background Color"]	= "Hintergrundfarbe",
      ["Changes the background color for the frame."]	= "Ver\195\164ndert die Hintergrundfarbe des Fensters.",
      ["Highlight Glow"]	= "Hervorhebungsleuchten",
      ["Turns hightlight glow on and off."]	= "Schaltet das Hervorhebungsleuchten an und aus.",
      ["Rarity Coloring"]	= "Einf\195\164rbung nach Seltenheit",
      ["Turns rarity coloring on and off."]	= "Schaltet die Seltenheitseinf\195\164rbung (z.B. violett f\195\188r episch) von Gegenst\195\164nden an und aus.",

      ["Reset"]	= "Zur\195\188cksetzen",
      ["Reset the different colors."]	= "Setzt die Farbeinstellungen auf die Standardwerte zur\195\188ck.",
      ["Mouseover Color"]	= "Hervorhebungsfarbe",
      ["Returns your mouseover color to the default."]	= "Setzt die Hervorhebungsfarbe auf die Grundeinstellung zur\195\188ck.",
      ["Ammo Slot Color"]	= "Munitionspl\195\164tze",
      ["Returns your ammo slot color to the default."]	= "Setzt die Farbe der Munitionspl\195\164tze auf die Grundeinstellung zur\195\188ck.",
      ["Soul Slot Color"]	= "Seelensteinpl\195\164tze",
      ["Returns your soul slot color to the default."]	= "Setzt die Farbe der Seelensteinpl\195\164tze auf die Grundeinstellung zur\195\188ck.",
      ["Profession Slot Color"]	= "Berufe-Pl\195\164tze",
      ["Returns your profession slot color to the default."]	= "Setzt die Farbe der Berufe-Pl\195\164tze auf die Grundeinstellung zur\195\188ck.",
      ["Background"]	= "Hintergrund",
      ["Returns your frame background to the default."]	= "Setzt die Hintergrundfarbe auf die Grundeinstellung zur\195\188ck.",
      ["Plow!"]	= "Plow!",
      ["Organizes your bags."]	= "Sortiert deine Taschen.",
      ["- Note: This option only appears if you have MrPlow installed"]	= "- Hinweis: Diese Option erscheint nur wenn du das Addon MrPlow installiert hast.",

      ["Pick Locale"] = "Spache ausw\195\164hlen", 
      ["Sets the locale to use.  Will not take effect until you reload your UI."] = "Stellt die zu benutzende Sprachs ein. \195\132nderungen werden erst nach dem Neuladen des Interface aktiv.",

      ["%s ran in %s"]	= "%s ben\195\182tigte %s",
      ["Checking if bag %s is open"]	= "Pr\195\188fe, ob Tasche %s ge\195\182ffnet ist.",
      ["Opening bag %s"]	= "\195\150ffne Tasche %s",
      ["Closing bag %s"]	= "Schlie\195\159e Tasche %s",

      ["Normal used: %s, Soul used: %s, Prof used: %s, Ammo used %s, Ammo quantity %s."]	= "Pl\195\164tze belegt: %s, Seelensteine: %s, Berufe-Pl\195\164tze belegt: %s, Munitionspl\195\164tze belegt: %s, %s Schuss.",
      ["%s/%s Slots"]	= "%s/%s Pl\195\164tze",
      ["%s/%s Ammo"]	= "%s/%s Schuss",
      ["%s/%s Soul Shards"]	= "%s/%s Seelensplitter",
      ["%s/%s Profession Slots"]	= "%s/%s Berufe-Pl\195\164tze",
      
      ["Menu"] = "Men\195\188" 
   }
end)