--$Id: frFR.lua 20271 2006-12-13 01:50:38Z tazmanyak $-- 
local L = AceLibrary("AceLocale-2.2"):new("OneBag")
L:RegisterTranslations("frFR", function()
  return {

      ["Frame"] = "Fen\195\170tre",
      ["Frame Options"] = "Options de la fen\195\170tre pricipale",
      ["Columns"]       = "Colonnes",
      ["Sets the number of columns to use"]     = "Pour choisir le nombre de colonnes \195\160 utiliser",
      ["Scale"] = "Echelle",
      ["Sets the scale of the frame"]   = "Modifie la taille",
--      ["Strata"]        = true,
--      ["Sets the strata of the frame"]  = "Avancer/reculer",
--      ["Alpha"] = true,
      ["Sets the alpha of the frame"]   = "Modifie la transparence",
      ["Locked"]        = "V\195\169rouiller",
      ["Toggles the ability to move the frame"] = "V\195\169rouiller/D\195\169v\195\169rouiller",
      ["Clamped"]       = "Clamp",
      ["Toggles the ability to drag the frame off screen."]     = "Permet de garder la fen\195\170tre \195\160 l'\195\169cran",
--      ["Bag Break"] = true,
      ["Sets wether to start a new row at the beginning of a bag."] = "Permet de commencer un sac sur une nouvelle ligne",
      ["Vertical Alignment"] = "Alignement",
      ["Sets wether to have the extra spaces on the top or bottom."] = "Permet d'afficher les cases vides en haut ou en bas",
      ["Top"] = "Haut",
      ["Bottom"] = "Bas",

      ["Show"]  = "Affichage",
      ["Various Display Options"]       = "Options d'affichage",
      ["Counts"]        = "Compteur",
      ["Toggles showing the counts for special bags."]  = "Active le compteur pour les sacs sp\195\169ciaux",
--      ["Direction"]     = true,
      ["Forward"]       = "Ordre",
      ["Toggles direction the bags are shown"]  = "Changer l'ordre dans lequel les sacs sont affich\195\169s",
--      ["|cffff0000Reverse|r"]   = true,
--      ["|cff00ff00Forward|r"]   = true,
      ["Ammo Bag"]      = "Sacs de munitions",
      ["Turns display of ammo bags on and off."]        = "Bascule l'affichage des munitions",
      ["Soul Bag"]      = "Sacs d'\195\162me",
      ["Turns display of soul bags on and off."]        = "Bascule l'affichage des sacs d'\195\162me",
      ["Profession Bag"]        = "Sacs de profession",
      ["Turns display of profession bags on and off."]  = "Bascule l'affichage des sacs de profession",
      ["Backpack"] = "Sac \195\160 dos",
      ["Turns display of your backpack on and off."] = "Bascule l'affichage du sac \195\160 dos",
      ["First Bag"] = "Sac 1",
      ["Turns display of your first bag on and off."] = "Bascule l'affichage du premier sac",
      ["Second Bag"] = "Sac 2",
      ["Turns display of your second bag on and off."] = "Bascule l'affichage du second sac",
      ["Third Bag"] = "Sac 3",
      ["Turns display of your third bag on and off."] = "Bascule l'affichage de troisi\195\168me sac",
      ["Fourth Bag"] = "Sac 4",
      ["Turns display of your fourth bag on and off."] = "Bascule l'affichage du quatri\195\168me sac",
      ["'s Bags"] = " : Inventaire",

      ["Colors"]        = "Couleurs",
      ["Different color code settings."]        = "Pour modifier les codes couleur",
      ["Mouseover Color"]       = "Mouseover",
      ["Changes the highlight color for when you mouseover a bag slot."] = "Couleur de l'aura quand vous passez la souris sur un objet",
      ["Ammo Bag Color"]        = "Sac de munitions",
      ["Changes the highlight color for Ammo Bags."]    = "Change la couleur du cadre",
      ["Soul Bag Color"]        = "Sac d'\195\162me",
      ["Changes the highlight color for Soul Bags."]    = "Change la couleur du cadre",
      ["Profession Bag Color"]  = "sac de profession",
      ["Changes the highlight color for Profession Bags."]      = "Change la couleur du cadre",
      ["Background Color"]      = "Arri\195\168re plan",
      ["Changes the background color for the frame."]   = "Change la couleur de fond de OneBag",
      ["Highlight Glow"]        = "Effet lumineux",
      ["Turns hightlight glow on and off."]     = "Active l'effet lumineux des cadres",
      ["Rarity Coloring"]       = "Raret\195\169",
      ["Turns rarity coloring on and off."]     = "Cadre coloré selon la raret\195\169",

      ["Reset"] = "Remise \195\160 z\195\169ro",
      ["Reset the different colors."]   = "Recharge les param\195\168tres de couleur par d\195\169faut",
      ["Mouseover Color"]       = "Mouseover",
      ["Returns your mouseover color to the default."]  = "Mouseover",
      ["Ammo Slot Color"]       = "Munition",
      ["Returns your ammo slot color to the default."]  = "Munition",
      ["Soul Slot Color"]       = "Pierre d'\195\162me",
      ["Returns your soul slot color to the default."]  = "Pierre d'\195\162me",
      ["Profession Slot Color"] = "Profession",
      ["Returns your profession slot color to the default."]    = "Profession",
      ["Background"]    = "Fond",
      ["Returns your frame background to the default."] = "Fond",
      ["Plow!"] = "Mr Plow!",
      ["Organizes your bags."]  = "R\195\169organise vos sacs",
      ["- Note: This option only appears if you have MrPlow installed"] = "- Note: cette option ne fonctionnera que si vous avez MrPlow d'install\195\169",

      ["Pick Locale"] = "Choisir une langue",
      ["Sets the locale to use.  Will not take effect until you reload your UI."] = "Vous permet de s\195\169lectionner la langue a utiliser pour la traduction. Ne sera pris en compte qu'apres un rechargement de l'interface.",

--      ["%s ran in %s"]  = true,
--      ["Checking if bag %s is open"]    = true,
--      ["Opening bag %s"]        = true,
--      ["Closing bag %s"]        = true,

--      ["Normal used: %s, Soul used: %s, Prof used: %s, Ammo used %s, Ammo quantity %s."]        = true,
      ["%s/%s Slots"]   = "%s/%s places",
      ["%s/%s Ammo"]    = "%s/%s munitions",
      ["%s/%s Soul Shards"]     = "%s/%s fragments",
      ["%s/%s Profession Slots"]        = "%s/%s de profession",

      ["Menu"] = "Menu"
}
end)