--$Id: zhCN.lua 14762 2006-10-22 04:06:29Z ckknight $-- 
-- zhCN localization by hk2717
local L = AceLibrary("AceLocale-2.2"):new("OneBag")
L:RegisterTranslations("zhTW", function()
    return {
		["Frame"]	= "框架",
		["Frame Options"]	= "框架設定",
		["Columns"]	= "欄數",
		["Sets the number of columns to use"]	= "設定每行的背包格子數量",
		["Scale"]	= "縮放",
		["Sets the scale of the frame"]	= "設定框架縮放比例",
		["Strata"]	= "層級",
		["Sets the strata of the frame"]	= "設定框架顯示優先級",
		["Alpha"]	= "透明度",
		["Sets the alpha of the frame"]	= "設定框架透明度",
		["Locked"]	= "鎖定",
		["Toggles the ability to move the frame"]	= "切換是否鎖定框架位置",
		["Clamped"]	= "限制",
		["Toggles the ability to drag the frame off screen."]	= "切換是否限制框架位置使其不能被拖動到螢幕邊緣之外。",
		["Bag Break"] = "背包分隔",
		["Sets wether to start a new row at the beginning of a bag."] = "設定是否在背包的起始位置前增加一格。",
		["Vertical Alignment"] = "垂直對齊",
		["Sets wether to have the extra spaces on the top or bottom."] = "設定是否在頂端或底端顯示額外的空間。",
		["Top"] = "頂端",
		["Bottom"] = "底端",
		
		["Show"]	= "顯示",
		["Various Display Options"]	= "各種顯示設定",
		["Counts"]	= "計數",
		["Toggles showing the counts for special bags."]	= "切換是否顯示特殊背包的格子計數。",
		["Direction"]	= "方向",
		["Forward"]	= "正向",
		["Toggles direction the bags are shown"]	= "切換背包顯示順序",
		["|cffff0000Reverse|r"]	= "|cffff0000反向|r",
		["|cff00ff00Forward|r"]	= "|cff00ff00正向|r",
		["Ammo Bag"]	= "彈藥袋",
		["Turns display of ammo bags on and off."]	= "切換是否顯示彈藥袋。",
		["Soul Bag"]	= "靈魂袋",
		["Turns display of soul bags on and off."]	= "切換是否顯示靈魂袋。",
		["Profession Bag"]	= "專業袋",
		["Turns display of profession bags on and off."]	= "切換是否顯示專業袋。",
		["Backpack"] = "背包",
		["Turns display of your backpack on and off."] = "切換是否顯示背包。",
		["First Bag"] = "第一個背包",
		["Turns display of your first bag on and off."] = "切換是否顯示第一個包。",
		["Second Bag"] = "第二個背包",
		["Turns display of your second bag on and off."] = "切換是否顯示第二個包。",
		["Third Bag"] = "第三個背包",
		["Turns display of your third bag on and off."] = "切換是否顯示第三個包。",
		["Fourth Bag"] = "第四個背包",
		["Turns display of your fourth bag on and off."] = "切換是否顯示第四個包。",
		["'s Bags"] = "的背包",		
		
		["Colors"]	= "顏色",
		["Different color code settings."]	= "各種顏色設定。",
		["Mouseover Color"]	= "游標移至顏色",
		["Changes the highlight color for when you mouseover a bag slot."]	= "變更游標移至背包格子上時的高亮顏色。",
		["Ammo Bag Color"]	= "彈藥袋顏色",
		["Changes the highlight color for Ammo Bags."]	= "變更彈藥袋的高亮顏色。",
		["Soul Bag Color"]	= "靈魂袋顏色",
		["Changes the highlight color for Soul Bags."]	= "變更靈魂袋的高亮顏色。",
		["Profession Bag Color"]	= "專業袋顏色",
		["Changes the highlight color for Profession Bags."]	= "變更專業袋的高亮顏色。",
		["Background Color"]	= "背景顏色",
		["Changes the background color for the frame."]	= "變更框架背景顏色。",
		["Highlight Glow"]	= "高亮發光",
		["Turns hightlight glow on and off."]	= "開關高亮發光。",
		["Rarity Coloring"]	= "品質顏色",
		["Turns rarity coloring on and off."]	= "開關品質顏色。",
		
		["Reset"]	= "重置",
		["Reset the different colors."]	= "重置各種顏色設定",
		["Mouseover Color"]	= "游標移至顏色",
		["Returns your mouseover color to the default."]	= "重置游標移至顏色為預設設定。",
		["Ammo Slot Color"]	= "彈藥格顏色",
		["Returns your ammo slot color to the default."]	= "重置彈藥格顏色為預設設定。",
		["Soul Slot Color"]	= "靈魂格顏色",
		["Returns your soul slot color to the default."]	= "重置靈魂格顏色為預設設定。",
		["Profession Slot Color"]	= "專業格顏色",
		["Returns your profession slot color to the default."]	= "重置專業格顏色為預設設定。",
		["Background"]	= "背景",
		["Returns your frame background to the default."]	= "重置背景顏色為預設設定。",
		["Plow!"]	= "整理！",
		["Organizes your bags."]	= "整理你的背包。",
		["- Note: This option only appears if you have MrPlow installed"]	= "- 注意：只有當你安裝了Mr.Plow插件時才會出現此設定",
		
		["%s ran in %s"]	= "%s運行於%s下",
		["Checking if bag %s is open"]	= "檢測背包%s是否是打開狀態",
		["Opening bag %s"]	= "打開背包%s",
		["Closing bag %s"]	= "關閉背包%s",
			
		["Normal used: %s, Soul used: %s, Prof used: %s, Ammo used %s, Ammo quantity %s."]	= "普通背包已用：%s，靈魂袋已用：%s，專業袋已用：%s，彈藥袋已用：%s，彈藥品質：%s。",
		["%s/%s Slots"]	= "%s/%s背包",
		["%s/%s Ammo"]	= "%s/%s彈藥",
		["%s/%s Soul Shards"]	= "%s/%s靈魂碎片",
		["%s/%s Profession Slots"]	= "%s/%s專業袋",
        
		["Menu"] = "選單"
    }
end)