FeralSkills_Localization = {};

FeralSkills_Localization.enUS = {
	SKILL_GROWL = "Growl";
	SKILL_FERALCHARGE = "Feral Charge";
	SKILL_SWIPE = "Swipe";
	SKILL_ENRAGE = "Enrage";
	SKILL_FAERIEFIREFERAL = "Faerie Fire (Feral)";
	SKILL_DEMORALIZINGROAR = "Demoralizing Roar";
	SKILL_MAUL = "Maul";
	SKILL_RIP = "Rip";
	SKILL_FEROCIOUSBITE = "Ferocious Bite";
	SKILL_RAKE = "Rake";
	SKILL_COWER = "Cower";
	SKILL_CLAW = "Claw";
	SKILL_TIGERSFURY = "Tiger's Fury";
	SKILL_POUNCE = "Pounce";
	SKILL_RAVAGE = "Ravage";
	SKILL_SHRED = "Shred";
	SKILL_CATFORM = "Cat Form";
	SKILL_BEARFORM = "Bear Form";
	SKILL_DIREBEARFORM = "Dire Bear Form";
	SKILL_TRAVELFORM = "Travel Form";
	SKILL_AQUATICFORM = "Aquatic Form";
	SKILL_PROWL = "Prowl";
	ENERGYCOSTDETECTIONTEXT = "Energy";
	MOUNTDETECTIONTEXT = "Increases speed";
}

FeralSkills_Localization.frFR = {
	SKILL_GROWL = "Grogner";
	SKILL_FERALCHARGE = "Charge farouche";
	SKILL_SWIPE = "Balayage";
	SKILL_ENRAGE = "Enrager";
	SKILL_FAERIEFIREFERAL = "Lucioles (farouche)";
	SKILL_DEMORALIZINGROAR = "Grognement d'intimidation";
	SKILL_MAUL = "Mutiler";
	SKILL_RIP = "D闁廻irure";
	SKILL_FEROCIOUSBITE = "Morsure F闁瀘ce";
	SKILL_RAKE = "Griffure";
	SKILL_COWER = "Se Recroqueviller";
	SKILL_CLAW = "Griffe";
	SKILL_TIGERSFURY = "Furie f闁榠ne";
	SKILL_POUNCE = "Traquenard";
	SKILL_RAVAGE = "Ravage";
	SKILL_SHRED = "Lambeau";
	SKILL_CATFORM = "Forme de F闁榠n";
	SKILL_BEARFORM = "Forme d鎶﹗rs";
	SKILL_DIREBEARFORM = "Forme d'ours sinistre";
	SKILL_TRAVELFORM = "Forme de voyage";
	SKILL_AQUATICFORM = "Forme aquatique";
	SKILL_PROWL = "R楝眅r";
	ENERGYCOSTDETECTIONTEXT = "d'闁歟rgie";
	MOUNTDETECTIONTEXT = "Augmente la vitesse de mouvement";
}

FeralSkills_Localization.deDE = {
	SKILL_GROWL = "Knurren";
	SKILL_FERALCHARGE = "Wilde Attacke";
	SKILL_SWIPE = "Prankenhieb";
	SKILL_ENRAGE = "Wutanfall";
	SKILL_FAERIEFIREFERAL = "Feenfeuer (Tiergestalt)";
	SKILL_DEMORALIZINGROAR = "Demoralisierendes Gebr\195\188ll";
	SKILL_MAUL = "Zermalmen";
	SKILL_RIP = "Zerfetzen";
	SKILL_FEROCIOUSBITE = "Wilder Biss";
	SKILL_RAKE = "Krallenhieb";
	SKILL_COWER = "Ducken";
	SKILL_CLAW = "Klaue";
	SKILL_TIGERSFURY = "Tigerfuror";
	SKILL_POUNCE = "Anspringen";
	SKILL_RAVAGE = "Verheeren";
	SKILL_SHRED = "Schreddern";
	SKILL_CATFORM = "Katzengestalt";
	SKILL_BEARFORM = "B\195\164rengestalt";
	SKILL_DIREBEARFORM = "Terrorb\195\164rengestalt";
	SKILL_TRAVELFORM = "Reisegestalt";
	SKILL_AQUATICFORM = "Wassergestalt";
	SKILL_PROWL = "Schleichen";
	ENERGYCOSTDETECTIONTEXT = "Energie";
	MOUNTDETECTIONTEXT = "Erh\195\182hte Geschwindigkeit";
}

FeralSkills_Localization.enGB = {
	SKILL_GROWL = "Growl";
	SKILL_FERALCHARGE = "Feral Charge";
	SKILL_SWIPE = "Swipe";
	SKILL_ENRAGE = "Enrage";
	SKILL_FAERIEFIREFERAL = "Faerie Fire (Feral)";
	SKILL_DEMORALIZINGROAR = "Demoralizing Roar";
	SKILL_MAUL = "Maul";
	SKILL_RIP = "Rip";
	SKILL_FEROCIOUSBITE = "Ferocious Bite";
	SKILL_RAKE = "Rake";
	SKILL_COWER = "Cower";
	SKILL_CLAW = "Claw";
	SKILL_TIGERSFURY = "Tiger's Fury";
	SKILL_POUNCE = "Pounce";
	SKILL_RAVAGE = "Ravage";
	SKILL_SHRED = "Shred";
	SKILL_CATFORM = "Cat Form";
	SKILL_BEARFORM = "Bear Form";
	SKILL_DIREBEARFORM = "Dire Bear Form";
	SKILL_TRAVELFORM = "Travel Form";
	SKILL_AQUATICFORM = "Aquatic Form";
	SKILL_PROWL = "Prowl";
	ENERGYCOSTDETECTIONTEXT = "Energy";
	MOUNTDETECTIONTEXT = "Increases speed";
}

FeralSkills_Localization.koKR = {
	SKILL_GROWL = "Growl";
	SKILL_FERALCHARGE = "Feral Charge";
	SKILL_SWIPE = "Swipe";
	SKILL_ENRAGE = "Enrage";
	SKILL_FAERIEFIREFERAL = "Faerie Fire (Feral)";
	SKILL_DEMORALIZINGROAR = "Demoralizing Roar";
	SKILL_MAUL = "Maul";
	SKILL_RIP = "Rip";
	SKILL_FEROCIOUSBITE = "Ferocious Bite";
	SKILL_RAKE = "Rake";
	SKILL_COWER = "Cower";
	SKILL_CLAW = "Claw";
	SKILL_TIGERSFURY = "Tiger's Fury";
	SKILL_POUNCE = "Pounce";
	SKILL_RAVAGE = "Ravage";
	SKILL_SHRED = "Shred";
	SKILL_CATFORM = "Cat Form";
	SKILL_BEARFORM = "Bear Form";
	SKILL_DIREBEARFORM = "Dire Bear Form";
	SKILL_TRAVELFORM = "Travel Form";
	SKILL_AQUATICFORM = "Aquatic Form";
	SKILL_PROWL = "Prowl";
	ENERGYCOSTDETECTIONTEXT = "Energy";
	MOUNTDETECTIONTEXT = "Increases speed";
}

FeralSkills_Localization.zhCN = {
	SKILL_GROWL = "低吼";
	SKILL_FERALCHARGE = "野性冲锋";
	SKILL_SWIPE = "重击";
	SKILL_ENRAGE = "狂怒";
	SKILL_FAERIEFIREFERAL = "精灵之火（野性）";
	SKILL_DEMORALIZINGROAR = "挫志咆哮";
	SKILL_MAUL = "槌击";
	SKILL_RIP = "撕扯";
	SKILL_FEROCIOUSBITE = "凶猛撕咬";
	SKILL_RAKE = "扫击";
	SKILL_COWER = "畏缩";
	SKILL_CLAW = "爪击";
	SKILL_TIGERSFURY = "猛虎之怒";
	SKILL_POUNCE = "突袭";
	SKILL_RAVAGE = "毁灭";
	SKILL_SHRED = "撕碎";
	SKILL_CATFORM = "猎豹形态";
	SKILL_BEARFORM = "熊形态";
	SKILL_DIREBEARFORM = "巨熊形态";
	SKILL_TRAVELFORM = "旅行形态";
	SKILL_AQUATICFORM = "水栖形态";
	SKILL_PROWL = "潜行";
	ENERGYCOSTDETECTIONTEXT = "能量";
	MOUNTDETECTIONTEXT = "速度";
}

FeralSkills_Localization.zhTW = {
	SKILL_GROWL = "Growl";
	SKILL_FERALCHARGE = "Feral Charge";
	SKILL_SWIPE = "Swipe";
	SKILL_ENRAGE = "Enrage";
	SKILL_FAERIEFIREFERAL = "Faerie Fire (Feral)";
	SKILL_DEMORALIZINGROAR = "Demoralizing Roar";
	SKILL_MAUL = "Maul";
	SKILL_RIP = "Rip";
	SKILL_FEROCIOUSBITE = "Ferocious Bite";
	SKILL_RAKE = "Rake";
	SKILL_COWER = "Cower";
	SKILL_CLAW = "Claw";
	SKILL_TIGERSFURY = "Tiger's Fury";
	SKILL_POUNCE = "Pounce";
	SKILL_RAVAGE = "Ravage";
	SKILL_SHRED = "Shred";
	SKILL_CATFORM = "Cat Form";
	SKILL_BEARFORM = "Bear Form";
	SKILL_DIREBEARFORM = "Dire Bear Form";
	SKILL_TRAVELFORM = "Travel Form";
	SKILL_AQUATICFORM = "Aquatic Form";
	SKILL_PROWL = "Prowl";
	ENERGYCOSTDETECTIONTEXT = "Energy";
	MOUNTDETECTIONTEXT = "Increases speed";
}

FeralSkills_Localization.ruRU = {
	SKILL_GROWL = "Growl";
	SKILL_FERALCHARGE = "Feral Charge";
	SKILL_SWIPE = "Swipe";
	SKILL_ENRAGE = "Enrage";
	SKILL_FAERIEFIREFERAL = "Faerie Fire (Feral)";
	SKILL_DEMORALIZINGROAR = "Demoralizing Roar";
	SKILL_MAUL = "Maul";
	SKILL_RIP = "Rip";
	SKILL_FEROCIOUSBITE = "Ferocious Bite";
	SKILL_RAKE = "Rake";
	SKILL_COWER = "Cower";
	SKILL_CLAW = "Claw";
	SKILL_TIGERSFURY = "Tiger's Fury";
	SKILL_POUNCE = "Pounce";
	SKILL_RAVAGE = "Ravage";
	SKILL_SHRED = "Shred";
	SKILL_CATFORM = "Cat Form";
	SKILL_BEARFORM = "Bear Form";
	SKILL_DIREBEARFORM = "Dire Bear Form";
	SKILL_TRAVELFORM = "Travel Form";
	SKILL_AQUATICFORM = "Aquatic Form";
	SKILL_PROWL = "Prowl";
	ENERGYCOSTDETECTIONTEXT = "Energy";
	MOUNTDETECTIONTEXT = "Increases speed";
}

