if (GetLocale()=="zhTW") then

----------------------------------------------------------------------------------------------------
-- Chinese Simplified Localizable Strings
----------------------------------------------------------------------------------------------------

-- For Binding.xml
BINDING_HEADER_QUESTHISTORY = "任務歷史庫";
BINDING_NAME_QUESTHISTORYTOGGLE = "顯示任務歷史庫";

-- Displayed when QuestHistory is loaded
QUESTHISTORY_LOAD_TEXT = "Jasters\226\128\153 QuestHistory v%0.2f 插件已加載 (由 Dsanai 更新)";
QUESTHISTORY_EARTH_HELPTEXT = "顯示你曾經做過的任務記錄";

-- QuestHistoryFrame text strings
QUESTHISTORY_FRAME_TITLE = "任務歷史庫";
QUESTHISTORY_TITLE = "";
QUESTHISTORY_TITLE_FORMAT_SINGULAR = "%s - 共1個任務";
QUESTHISTORY_TITLE_FORMAT_PLURAL = "%s - 共%d個任務";
QUESTHISTORY_SORT_DROPDOWN_TEXT = "排序:";
QUESTHISTORY_ACCEPTEDSORT_TEXT = "#";
QUESTHISTORY_TITLESORT_TEXT = "任務名";
QUESTHISTORY_LEVELSORT_TEXT = "等級";
QUESTHISTORY_CATEGORYSORT_TEXT = "類別";
QUESTHISTORY_TAGSORT_TEXT = "標記";
QUESTHISTORY_COMPLETEDSORT_TEXT = "是否完成";
QUESTHISTORY_CANCEL_TEXT = "取消";
QUESTHISTORY_OPTIONS_TEXT = "選項";
QUESTHISTORY_CLEAR_TEXT = "清空";
QUESTHISTORY_SEARCH_TEXT = "搜索";
QUESTHISTORY_SUBMIT_TEXT = "開始搜索";

-- For the Sort Dropdown list
SORT_ACCEPTED = "接受任務時間";
SORT_TITLE = "任務名";
SORT_LEVEL = "等級";
SORT_CATEGORY = "類別";
SORT_COMPLETED = "完成任務時間";
SORT_TAG = "標記";
SORT_XP = "經驗值獎勵";
SORT_MONEY = "金錢獎勵";
SORT_GIVER = "接受NPC";
SORT_COMPLETER = "結束NPC";

-- QuestHistoryDetailFrame text strings
QUESTHISTORY_DETAIL_TITLE = "";
QUESTHISTORY_DETAIL_TITLE_FORMAT = "%s - 等級 %s%s";
QUESTHISTORY_LEVEL_ACCEPTED_TITLE = "接受等級";
QUESTHISTORY_LEVEL_LOGGED_TITLE = "記錄等級";
QUESTHISTORY_LEVEL_COMPLETED_TITLE = "完成等級";
QUESTHISTORY_XP_REWARDED_TITLE = "經驗獎勵";
QUESTHISTORY_MONEY_REWARDED_TITLE = "金錢獎勵";
QUESTHISTORY_DETAIL_NOTES_TITLE = "備注";
QUESTHISTORY_QUEST_GIVER_TITLE = "接受NPC";
QUESTHISTORY_QUEST_COMPLETER_TITLE = "結束NPC";
QUESTHISTORY_ACCEPTED_LOCATION_TITLE = "接受地點";
QUESTHISTORY_COMPLETED_LOCATION_TITLE = "完成地點";
QUESTHISTORY_TIME_ACCEPTED_TITLE = "接受時間";
QUESTHISTORY_TIME_LOGGED_TITLE = "記錄時間";
QUESTHISTORY_TIME_COMPLETED_TITLE = "完成時間";
QUESTHISTORY_TIME_FORMAT = "%02d:%02d:%02d:%02d";
QUESTHISTORY_TIMES_ABANDONED_TITLE = "放棄次數";
QUESTHISTORY_TIMES_FAILED_TITLE = "失敗次數";
QUESTHISTORY_EDIT_TEXT = "編輯";
QUESTHISTORY_SAVE_TEXT = "保存";
QUESTHISTORY_EXIT_TEXT = "退出";
QUESTHISTORY_NEXT_TEXT = "下一個";
QUESTHISTORY_PREVIOUS_TEXT = "上一個";

-- QuestHistoryOptionsFrame text strings
QUESTHISTORY_OPTIONS_MENU = "任務歷史庫選項";
QUESTHISTORY_OKAY_TEXT = "確定";
QUESTHISTORY_SHOW = "顯示";
QUESTHISTORY_SHOW_ABANDONED = "放棄";
QUESTHISTORY_SHOW_CURRENT = "當前";
QUESTHISTORY_SHOW_COMPLETED = "完成";
QUESTHISTORY_CHARACTER_DROPDOWN_TEXT = "角色:";
QUESTHISTORY_LOG = "記錄";
QUESTHISTORY_LOG_LEVEL = "任務等級";
QUESTHISTORY_LOG_CATEGORY = "任務類別";
QUESTHISTORY_LOG_TAG = "任務標記";
QUESTHISTORY_LOG_COMPLETED_ORDER = "任務完成順序";
QUESTHISTORY_LOG_DESCRIPTION = "任務描述";
QUESTHISTORY_LOG_OBJECTIVES = "任務目標";
QUESTHISTORY_LOG_OBJECTIVES_STATUS = "任務目標完成情況";
QUESTHISTORY_LOG_REWARDS = "任務獎勵";
QUESTHISTORY_LOG_CHOICES = "任務獎勵選擇";
QUESTHISTORY_LOG_SPELLS = "任務技能";
QUESTHISTORY_LOG_REWARD_MONEY = "任務金錢獎勵";
QUESTHISTORY_LOG_BACKGROUND_MATERIAL = "背景圖片";
QUESTHISTORY_LOG_REQUIRED_MONEY = "任務所需金錢";
QUESTHISTORY_LOG_XP_REWARD = "任務經驗值獎勵";
QUESTHISTORY_LOG_QUEST_GIVER = "接受NPC";
QUESTHISTORY_LOG_QUEST_COMPLETER = "完成NPC";
QUESTHISTORY_LOG_ACCEPTED_LEVEL = "接受任務時等級";
QUESTHISTORY_LOG_COMPLETED_LEVEL = "完成任務時等級";
QUESTHISTORY_LOG_ACCEPTED_TIME = "接受時間";
QUESTHISTORY_LOG_COMPLETED_TIME = "完成時間";
QUESTHISTORY_LOG_ACCEPTED_LOCATION = "接受地點";
QUESTHISTORY_LOG_COMPLETED_LOCATION = "完成地點";
QUESTHISTORY_ADD_TEXT = "添加";
QUESTHISTORY_PURGE_TEXT = "清空";
QUESTHISTORY_DELETE_TEXT = "刪除";
QUESTHISTORY_REPAIR = "修復";
QUESTHISTORY_REMOVE_PORT_QUESTS = "移除過渡任務";
QUESTHISTORY_REMOVE_DUPLICATES = "移除重復任務";
QUESTHISTORY_OTHER = "其他";
QUESTHISTORY_ALLOW_EDITING = "允許編輯";
QUESTHISTORY_ALLOW_DELETING = "允許刪除";
QUESTHISTORY_LOG_PORT_QUESTS = "記錄過渡任務";
QUESTHISTORY_OPTION_TOOLTIP_SHOW_ABANDONED = "在任務歷史庫的主窗口顯示放棄的任務.";
QUESTHISTORY_OPTION_TOOLTIP_SHOW_CURRENT = "在任務歷史庫的主窗口顯示當前的任務.";
QUESTHISTORY_OPTION_TOOLTIP_SHOW_COMPLETED = "在任務歷史庫的主窗口顯示完成的任務.";
QUESTHISTORY_OPTION_TOOLTIP_SELECT_CHARACTER = "選擇角色.";
QUESTHISTORY_OPTION_TOOLTIP_SELECT_COLOR = "選擇顯示任務狀態的顏色.";
QUESTHISTORY_OPTION_TOOLTIP_LOG_LEVEL = "記錄任務等級.";
QUESTHISTORY_OPTION_TOOLTIP_LOG_CATEGORY = "記錄任務分類.";
QUESTHISTORY_OPTION_TOOLTIP_LOG_TAG = "記錄任務標志(比如:精英,地下城).";
QUESTHISTORY_OPTION_TOOLTIP_LOG_COMPLETED_ORDER = "記錄任務完成順序. 注意: 禁止這個功能的話任務將不會被標記成完成.";
QUESTHISTORY_OPTION_TOOLTIP_LOG_DESCRIPTION = "記錄任務描述.";
QUESTHISTORY_OPTION_TOOLTIP_LOG_OBJECTIVES = "記錄任務目標";
QUESTHISTORY_OPTION_TOOLTIP_LOG_OBJECTIVES_STATUS = "記錄任務目標完成情況（如：0/1 已完成）";
QUESTHISTORY_OPTION_TOOLTIP_LOG_REWARDS = "記錄任務物品獎勵\n\n這些物品是在你完成任務時獲得的";
QUESTHISTORY_OPTION_TOOLTIP_LOG_CHOICES = "記錄任務選擇物品獎勵\n\n這些物品是在你完成任務時選擇的";
QUESTHISTORY_OPTION_TOOLTIP_LOG_SPELLS = "記錄任務技能獎勵";
QUESTHISTORY_OPTION_TOOLTIP_LOG_REWARD_MONEY = "記錄任務金錢獎勵";
QUESTHISTORY_OPTION_TOOLTIP_LOG_BACKGROUND_MATERIAL = "記錄任務背景圖片（通常是空的）";
QUESTHISTORY_OPTION_TOOLTIP_LOG_REQUIRED_MONEY = "記錄完成任務所需的金錢";
QUESTHISTORY_OPTION_TOOLTIP_LOG_XP_REWARD = "記錄完成任務所獎勵的經驗值";
QUESTHISTORY_OPTION_TOOLTIP_LOG_QUEST_GIVER = "記錄給予任務的NPC";
QUESTHISTORY_OPTION_TOOLTIP_LOG_QUEST_COMPLETER = "記錄結束任務的NPC";
QUESTHISTORY_OPTION_TOOLTIP_LOG_ACCEPTED_LEVEL = "記錄接受任務時玩家的等級";
QUESTHISTORY_OPTION_TOOLTIP_LOG_COMPLETED_LEVEL = "記錄完成任務時玩家的等級";
QUESTHISTORY_OPTION_TOOLTIP_LOG_ACCEPTED_TIME = "記錄接受任務時的遊戲時間";
QUESTHISTORY_OPTION_TOOLTIP_LOG_COMPLETED_TIME = "記錄完成任務時的遊戲時間";
QUESTHISTORY_OPTION_TOOLTIP_LOG_ACCEPTED_LOCATION = "記錄接受任務的地點";
QUESTHISTORY_OPTION_TOOLTIP_LOG_COMPLETED_LOCATION = "記錄完成任務的地點";
QUESTHISTORY_OPTION_TOOLTIP_ADD_QUEST = "打開一個編輯窗口以手動添加一個新任務"
QUESTHISTORY_OPTION_TOOLTIP_PURGE = "清除目前顯示的角色的記錄中未選擇的數據";
QUESTHISTORY_OPTION_TOOLTIP_DELETE_CHARACTER = "完全刪除現在目前顯示的記錄\n\n不能刪除目前所遊戲的角色";
QUESTHISTORY_OPTION_TOOLTIP_REMOVE_PORT_QUESTS = "如果勾選,則清除如飛往奧伯丁之類的任務.";
QUESTHISTORY_OPTION_TOOLTIP_REMOVE_DUPLICATES = "如果選擇，修覆命令將會刪除那些有重復標題和描述的任務";
QUESTHISTORY_OPTION_TOOLTIP_REPAIR = "為所有角色修復任務歷史";
QUESTHISTORY_OPTION_TOOLTIP_ALLOW_EDITING = "允許編輯任務\n\n右鍵點擊一個任務即可進行編輯";
QUESTHISTORY_OPTION_TOOLTIP_ALLOW_DELETING = "允許刪除任務\n\nShift+右鍵點擊一個任務即可進行刪除";
QUESTHISTORY_OPTION_TOOLTIP_LOG_PORT_QUESTS = "允許記錄如飛往奧伯丁之類的過渡任務.";

-- QuestHistoryConfirmFrame text strings
QUESTHISTORY_CONFIRM_TEXT = "是否確定？";
QUESTHISTORY_PURGE_CONFIRM_EXPLANATION = "繼續這個操作將會清除目前顯示的角色的記錄\n\n在前一個窗口中任何未選擇的數據都將從 SavedVariables.lua 中刪除\n\n這些數據將無法恢復，所以建議您在繼續操作前備份 SavedVariables.lua";
QUESTHISTORY_DELETE_CONFIRM_EXPLANATION = "繼續這個操作將會完全刪除目前顯示的角色的記錄\n\n這些數據將無法恢復，所以建議您在繼續操作前備份 SavedVariables.lua";
QUESTHISTORY_REPAIR_CONFIRM_EXPLANATION = "繼續這個操作將會嘗試修復所有角色的記錄，有時可以解決一些錯誤\n\n另外，如果在前一個窗口中選擇的話，這個操作將會清除重復的任務及奧伯丁和米奈希爾港之間的港口任務\n\n因為這個操作會清除一部分數據，所以建議您在繼續操作前備份 SavedVariables.lua";

-- QuestHistoryEditFrame text strings
QUESTHISTORY_EDIT_TITLE_TEXT = "任務名";
QUESTHISTORY_EDIT_OBJECTIVES_TEXT = "任務目標";
QUESTHISTORY_EDIT_DESCRIPTION_TEXT = QUEST_DESCRIPTION;
QUESTHISTORY_ACCEPTED_TITLE = "接受";
QUESTHISTORY_LEVEL_TITLE = "等級";
QUESTHISTORY_COMPLETED_TITLE = "完成";
QUESTHISTORY_CATEGORY_TITLE = "類別";
QUESTHISTORY_TAG_TITLE = "標記";
QUESTHISTORY_ZONE_TITLE = "地區";
QUESTHISTORY_X_TITLE = "X";
QUESTHISTORY_Y_TITLE = "Y";


end